### ISSUE TITLE
Distribution Model

### ISSUE THREAD

**Issue by sumthinknew** [kinecosystem/rewards-engine#1]
This does not offer, even relatively, equal distribution. Imagine we have 10 users, their names are 1-10 and their total stakes equal to the same number (e.g. ‘7’ has 7KIN). Imagine 1,2,3,4, and 5 all use service A, totaling 10KIN in transactions, and 7,8, and 9 use service B, totaling 5KIN in transactions, while also doing 2KIN worth of transactions with service A. Even though service A did more volume and had a larger number of users, only service B will be rewarded because of the accounts corresponding to the users. There is no reason that service B should be rewarded and service A neglected. 
Furthermore, the fact that a user’s stake will only be credited for the service in which their transaction volume was greatest, also provides disincentive for innovation. Disincentivizing anyone offering services that may not be the majority of a typical user’s transaction volume. For example, just because each day I spend more money on groceries than I do on Uber does not mean that I can simply not pay my Uber driver. The Uber driver makes up for the smaller transactions with the number of transaction he/she does with multiple consumers. However, if these small transactions are simply disregarded because they are an insufficient portion of the individual consumer's budget, it is not possible for the Uber driver to sum his/her added value.  Often services are cooperative and auxiliary, such as taking an Uber to the grocery store or buying soda at a ballgame. However, in the case of the KRE, neither the Uber driver nor the soda vendor are getting paid. 
Also, contrary to the attitude in the paper, I like the idea of capitalists being able to stake their KIN to prevent against inflationary effects. If KIN holders are not suppose to protect against inflationary effects, why would their be a token distribution event? I am certainly patient and willing to contribute in building value. However, the interests of early adopters should be taken into consideration as well. Risk should be rewarded; we are at about 60% TDE price right now. This is not a complaint, but, rather, an indication of the risk being taken. We certainly did not participate out of the goodness our hearts to fund Kik.
 I hope these notes help.

**Comment by ryana** [comment]
Hey @sumthinknew how you doing? I'm excited to engage with you on this. Here are some thoughts:

>This does not offer, even relatively, equal distribution. Imagine we have 10 users, their names are 1-10 and their total stakes equal to the same number (e.g. ‘7’ has 7KIN). Imagine 1,2,3,4, and 5 all use service A, totaling 10KIN in transactions, and 7,8, and 9 use service B, totaling 5KIN in transactions, while also doing 2KIN worth of transactions with service A. Even though service A did more volume and had a larger number of users, only service B will be rewarded because of the accounts corresponding to the users. There is no reason that service B should be rewarded and service A neglected.

Keep in mind that Service A will not be "neglected." Service A will still get something, it'll just be smaller than what Service B gets.

Let's assume for the sake of simplicity that when it's all said and done, each user has the same balance they started with. In that case:

Users 1-5 will have their preferred service be A, and their sum of balances will be 15.
Users 7-9 will have their preferred service be B, and their sum of balances will be 24.

Total economy size is 39. While it's true that Service A did more volume and had more users, it is not neglected. It gets 15/39 of the daily reward and Service B gets 24/39.

While this may seem unfair, I believe you're making the mistake of only looking at a pathological case and applying across the board. That probably won't happen. You're also discounting the possibility that an app attracting people with higher KIN balances may be inherently more valuable.



>Furthermore, the fact that a user’s stake will only be credited for the service in which their transaction volume was greatest, also provides disincentive for innovation. Disincentivizing anyone offering services that may not be the majority of a typical user’s transaction volume. For example, just because each day I spend more money on groceries than I do on Uber does not mean that I can simply not pay my Uber driver. The Uber driver makes up for the smaller transactions with the number of transaction he/she does with multiple consumers. However, if these small transactions are simply disregarded because they are an insufficient portion of the individual consumer's budget, it is not possible for the Uber driver to sum his/her added value. Often services are cooperative and auxiliary, such as taking an Uber to the grocery store or buying soda at a ballgame. However, in the case of the KRE, neither the Uber driver nor the soda vendor are getting paid.

This one is interesting. I don't have an answer for it. Looking forward to seeing what KIN says about it, but one thing to keep in mind is that it may incentivize app developers to build more niche apps with silos of users. So like, KIN might not be used by grocery stores and Uber (services with very generalized user bases) but it will incentivize app developers to market their products and bring their own users into KIN. Those users may not use KIN for many other apps in the beginning.

**Comment by sumthinknew** [comment]
> Those users may not use KIN for many other apps in the beginning.
It seems this may be good to encourage a wider audience, but it certainly neglects the user base that is already established. The easiest customers to find are the ones already at the store - so to speak.

**Comment by oryband** [comment]
@sumthinknew 

>  Even though service A did more volume and had a larger number of users, only service B will be rewarded because of the accounts corresponding to the users.

Continuing on what @ryana said: The proposal states the rewards will be distributed *relatively* to the colored transaction volume. So no - B will not get everything and A will not be left with nothing. B will just get more because it accumulated more transactions with more value. A will get its part as well. The grocery store and Uber will both get their share. :)

> Furthermore, the fact that a user’s stake will only be credited for the service in which their transaction volume was greatest, also provides disincentive for innovation. Disincentivizing anyone offering services that may not be the majority of a typical user’s transaction volume ... However, in the case of the KRE, neither the Uber driver nor the soda vendor are getting paid.

As I explained above - The Uber driver and the soda vendor will be getting their share. If you are stating that they will get a very small share because the majority will be given to the grocery store - keep in mind that you will still need to pay them Kin for their services, so are still getting income. The Rewards Engine can be viewed as an added bonus on top of that, which is a mechanism to do the heavy-lifting task of kickstarting an economy, and get grocery stores, Uber drivers, and soda vendors to open up business ("digital services") on top of Kin.
