### ISSUE TITLE
Timing

### ISSUE THREAD

**Issue by AmirAlikhanzadeh** [kinecosystem/rewards-engine#19]
Considering that we are winding down and it’s towards the end of the year, I think as developers it would be hard to design, implement and release experiences adjusted to the new guidelines. While I generally support the changes, I do believe we need to have a bit more time for readjustment and education for the users.

**Comment by chaseeb** [comment]
Hey Amir! Just for the sake of clarity could you be more specific? I'll assume you are talking about KRE 2.0. If that's correct, which parts concern you? And how would you change the timing of them, specifically?

**Comment by AmirAlikhanzadeh** [comment]
Hi Chase,

Yes I am talking about the 2.0 Proposal. I have to spend some time and come up with something concrete, but I thought I could share this earlier. The fact that the users now have to spend a different amount of Kin requires education on our side and I just don’t think there’s enough time between now and Jan to do that since we as devs need to figure out the economy of it, then implement, test and finally release. We also need to strategize on the other covets of the proposal in terms of holding vs selling and continuous vs fixed term holds. All in all I feel like there are a lot of considerations and since my goal is to make sure we all have a thriving ecosystem to work in, I don’t wanna make kerk reaction moves and regret it in the long run.

**Comment by chaseeb** [comment]
Hey Amir. That's some great feedback. The whole point of this new process is to propose an ideas, start a discussion, improve and iterate before the proposals are voted on by the KF board.

I completely understand the re-education piece and how that will take some time. To add some context this is also why the proposal has weighted values on tx amounts. This will allow for a slow transition if necessary. So any app can continue doing things as they are currently doing, but it adds additional incentives for transitioning the economics of your app. It also allows smaller apps with less users to more fairly compete in the KRE by upping their tx values. The ultimate goal is to make the KRE as fair as possible for everyone, without penalizing apps for being too big or too small. And these conversations will help us get there.

Anyways, this is a great topic and look forward further discussions.

**Comment by ipscan** [comment]
Thanks for your contributions. KRE 2.0 has been adopted with a gradual curve on changes to payout calculation. Issue closed.
