### ISSUE TITLE
Formalization of method of commenting on proposals

### ISSUE THREAD

**Issue by hitwill** [kinecosystem/rewards-engine#20]
I couldn't find any instructions on how to comment on someone's proposal. Should we create a pull request or just raise it as an issue? Would be great to have those instructions formalized.

**Comment by chaseeb** [comment]
Great question Will. A lot of this should be determined by what works best for people. What would you suggest?

**Comment by ipscan** [comment]
Thanks everyone for this discussion. I've updated the HowtoContribute section to clarify to use issues. Keeping this issue open so that the conversation on further improvements can continue.

**Comment by hitwill** [comment]
> Great question Will. A lot of this should be determined by what works best for everyone. What would you suggest?

Thanks, I think opening an issue and linking to the proposal would work well, without having to create the extra work for maintainers by doing a PR.

**Comment by chaseeb** [comment]
That's a great idea!

**Comment by ipscan** [comment]
Thanks for your contributions. A tutorial on how to contribute was released and your suggestion of linking to proposals in question has been implemented into the HowToContribute section. Ease of contribution will continue to be iterated upon. Issue closed.
