### ISSUE TITLE
The KRE as a bank

### ISSUE THREAD

**Issue by hitwill** [kinecosystem/rewards-engine#21]
I am placing this here first, to see if it is worth submitting as a fully fleshed proposal for consideration. 

### Holding Kin proposal
This idea stems from [Kin Improvement Proposal - KRE V2.0](https://github.com/kinecosystem/rewards-engine/blob/master/improvement-proposals/kik_kre_2_0.md#3-holding) regarding a reward to developers for holding.

In the proposal linked above, the KRE rewards developers for holding/ locking their Kin for a period of time. The idea is to encourage holding and limit the supply of Kin being sold after every KRE period.

### Extending the proposal
We can extend this further by using the analogy of a Central Bank (mints new currency) and a Government (first spender of newly minted currency). Depending on its goal, the government has the option of borrowing from the central bank (by minting new currency), or borrowing from the populace, in the form of bonds. To lower inflation, a government would prefer to issue bonds to its populace over minting new currency.

The KRE could work in a similar way, by taking fixed term loans from Kin holders (not just developers) and preferentially using that over releasing more Kin during a KRE period.

### An example
Currently, if the total KRE payout for a specific week is 1,000,000 Kin, then 1,000,000 Kin would be freshly minted and circulated into the economy. With this proposal, if the KRE had 5,000,000 Kin in its 'bonds account' from Kin holders, 0 extra Kin would be minted and circulated, but simply a portion of the Kin that was already in circulation, held in the bonds account, would go to developers.

With the arrangement above, the KF would have control of the actual Kin in circulation, by adjusting interest rates to encourage or reduce the amount of Kin going into the 'bond account'.

Another advantage is, Kin would be a stake-able coin, and such an arrangement adds more utility to the 'reward for hold' mechanism we are deriving this idea from.

**Comment by kikengineering** [comment]
Thanks for the detailed response!
We talked internally about proposing a more formal bond as you have described, but we think that there are a few regulatory issues. Bonds are considered securities and there are also issues with being indebted in general (and we wanted to avoid both). The holding track we wrote up addresses the problem in a similar (though less direct way) but we believe it does not have these issues.

**Comment by asparagusm** [comment]
I am an attorney,  while your suggestion is novel, it posses significant regulatory issues both on the lender and borrower side.   If it was developed in a legally compliant way,  there would be high ongoing regulatory compliance costs.

**Comment by WeviNest** [comment]
Referring to timelocked staking as a bond is how you get in trouble. However, timelocked staking would be a great addition to the KRE and allow investors to receive rewards for believing in the long term viability of the project.

**Comment by ipscan** [comment]
While this idea may be explored again in the future, as noted there are legal complications that stop it from being a part of the KRE as it stands today. Thanks for your contributions.
