### ISSUE TITLE
Multiple wallets owned by app

### ISSUE THREAD

**Issue by showered** [kinecosystem/rewards-engine#22]
It sounds like there is going to be an incentive for developers to run up a large balance of Kin inside their app's main wallet. 

To limit the damage of a potential hack, we at PeerBet hold a large portion of our Kin in cold storage. 

I wondered if it might be possible to add our cold storage wallets (validated with a memo) to a list of wallets that can be used for KRE calculations.

**Comment by kikengineering** [comment]
Good catch. Yes, this (or something very close to it) should definitely be done. If we allow each app to add a single (validated) cold storage wallet that would solve the problem and be easy enough to maintain. Thoughts?

**Comment by ipscan** [comment]
This issue has been pinned to be reviewed by @kikengineering to append their proposal

**Comment by ipscan** [comment]
Improvement proposal has been amended
