### ISSUE TITLE
KRE 2.0 - Holding - Continuous 

### ISSUE THREAD

**Issue by asparagusm** [kinecosystem/rewards-engine#23]
https://github.com/kinecosystem/rewards-engine/blob/master/improvement-proposals/kik_kre_2_0.md

Encouraging developers to save KIN, in essence, requires developers to change their behaviour ... to want to _preserve_ KIN in their wallet for their later future benefit (in this case to obtain a reward).  
In the continuous holding reward currently proposed,  the reward is calculated on the kin balance on a daily basis (paid out monthly).  If I am understanding the logic correctly the balance of the wallet could widely fluctuate on any particular day of the week and they would still be entitled to a reward at the end of the month even if their wallet balance was temporary at 0 for some days in the month (the opposite of saving behaviour).   I propose an alternative continuous holding model which better incentives 'holding' behaviour.

The logic is as follows:

1.  For each developer, get their wallet balance at the end of each day.
2.  At the end of the month,  check the daily balances for the month and then take the day with the lowest wallet balance (the Test Day)
3.  Calculate the holding reward for that month against the Test Day.  

The reward is still being computed on a daily basis and paid monthly however the reward is calculated based on the relevant day in that month that had the lowest wallet balance.  In doing so, developers are incentivised to not lower their balance. 

Some of the benefits over the current proposal include that it (i) actually encourages holding KIN (ii) ignores fluctuating wallet balances including developers who have a large volume of incoming and outgoing transactions i.e. they won't be getting a reward for holding a large balance just for a short period of time; (ii)  it also will be a disincentive to creating cartels amongst developers (i.e. transferring KIN around so many people can boost their daily payout by sharing large blocks of KIN) because when you transfer KIN out of your wallet, you will be potentially decreasing your own rewards for not exhibiting 'saving' behaviour.   Please let me know your thoughts on this proposal. 

Finally, please can you clarify what this means with an example 'Note that we have capped developers to receive a holding reward no greater than 50% of the size of their KRE wallet holdings divided by 365 days in a year.'

**Comment by kikengineering** [comment]
Thanks for the feedback!
For your last question, mathematically:
Payout_hold_i = min(w_i / sum(w_j for all apps j in A) * KRE_hold, w_i * 50% / 365)
What this effectively means (we can go back and reword that statement if it's unclear) is:
Suppose a developer's KRE wallet (or one they've specified is for cold storage) has 1000 Kin in it at the end of a day. The most the daily payout for holding would be is 1000 * 50% / 365 ~ 1.37 Kin (0.137% of the size of the wallet). We modelled this roughly after what would be paid out for a similarly-sized savings account being paid a 50% annual interest rate. The developer could be paid less than this if many other developers were holding Kin, and the Kin set aside to payout for this track was less than 0.137% of all of the holding wallets for KRE developers.

In terms of your actual proposal, at first glance it does sound better for the reasons you mentioned. We want to crunch some numbers and make sure that it actually does create less sell-pressure on aggregate and walk through the Cartel example you spoke about. We'll try and reply again later today.

**Comment by kikengineering** [comment]
After some discussion we think the correction direction is:
- Users will rewarded based on their lowest balance each day.
We think this will alleviate some of the issues with short-term collaboration of moving money around between apps, but be granular enough to reward developers. If we take the lowest balance over the course of a month we may run into some sunk cost issues. I.e. if a developer needs to move Kin to another wallet for a few days then their whole month of rewards would be gone for that segment of Kin. If a developer has a balance of 1000 Kin, moves 500 out, then 500 back shortly thereafter, from an ecosystem point of view, the aggregate buy and sell pressure is still the same. Thoughts?

**Comment by asparagusm** [comment]
Yes I think calculating the daily reward based on the lowest balance of the wallet throughout the day would alleviate some of these concerns.   I hope to see this incorporated.

---------------------

Next suggestion:

While in the proposal you state there is an implicit lock-in through this incentive,  I feel this implicity is weak seeing the reward is paid on a _per day_ basis.   While you are encouraging 'holding',  this doesn't carry through to the payout structure because you don't finally reward 'holding' behaviour  -  in essence you would be paying the daily reward on transient KIN balances when there was no intention on part of the developer to hold it in the first place.  That doesn't seem right and it was one of my concerns in my original post.   

I was thinking how you could strengthen this incentive to hold KIN for multiple days but not change the daily reward proposal or require a lockup.  One way you could do this is as follows:

1. At the end of the month, get all the lowest daily balances for each day for the month
2. Starting on the first day of the month (reward day), look 48 hours ahead (the adjustment day).  On the adjustment day,  if the wallet balance is less than the reward day THEN,  subtract from the reward day the difference between (the reward day minus the adjustment day).   Let the wallet balance of the reward day be the corrected amount. 
3.  Keep doing this until the end of the period, then calculate the holding reward to be paid to the user. 

In doing so you are testing your assumptions on a look forward basis that the KIN that's being rewarded was actually held.   This is a soft way to create a minimum holding period without requiring any kind of fixed lock up.  The KIN remains freely transferable.    If the developer didn't hold it the minimum period (in this case 72 hours), the user still receives a holding reward although it's just adjusted to reflect the KIN they actually ended up holding.   Could you see this having a place in the algo?

**Comment by kikengineering** [comment]
These are good points. There is a tradeoff in both incentive and technical complexities. There are some potential second order consequences that could arise, like a sunk cost fallacy. A developer could have one low day within a period - that now sets the ceiling for their payout within that period and there is no incentive to hold above the ceiling that is set by the low day.

Our view is that we should implement the current proposal as a simple starting point. If this does not create enough pressure we can submit an improvement proposal for a more aggressive holding reward schema in the future. 

By default, we would think we should keep it simple from both an understanding and technical perspective to give us flexibility to observe behaviour, learn, and iterate. There is a balance that will take some tinkering: strong enough hold incentives for holding for a long time vs developers "giving up" on holding when they need to move Kin around. 

By keeping it to daily it maintains simplicity and flexibility for developers to adapt to this new incentive framework and to start adjusting their behaviour. This can then evolve over time.

**Comment by ipscan** [comment]
Reviewed this issue, verified that latest amendment to KIP by Kik reflects changes. Thanks for your contributions.
