### ISSUE TITLE
Incentivizing Apps to deploy KIN modules

### ISSUE THREAD

**Issue by Polype01** [kinecosystem/rewards-engine#26]
Hi

My proposal is that whenever a new App is receiving KIN via the KRE for the first time, there will be some checks that will define extra distribution of KIN to the devs

**1ST KRE Appearance distribution:** 
A  first fixed amount of KIN will be distributed to the developers of the new App (ex: 1M KIN) for their very 1st KRE period by default

**KIN modules presence distribution**
The App will be monitored from a technical standpoint by Kin Foundation. 
The following KIN modules will also provide extra KIN if deployed within the App

- KIN Buy-in module -> KRE distributes 100000 KIN to the developers of the App
- KIN tourism feature module -> KRE distributes 100000 KIN to the developers of the App
- KIN discovery feature module -> KRE distributes 100000 KIN  to the developers of the App
- KIN spends. 
 a) If 1-5 relevant spends are found --> KRE distributes 100000 KIN to the developers of te App
 b) If 6-10 relevant spends are found --> KRE distributes extra 100000 KIN to the developers of the App 
c) If 11-20vrelevant spends are found.....

If all of the above modules are found --> KRE distributes an extra 500000 KIN

--> A total of 2M to be distributed to the App, once, if all boxes are checked.

 Kin Foundation will be able to make a periodic report on the Apps and to see which Apps deployed which modules. 

Then, from the second KRE period of the App, based on the activity and amount of users using actually the Buy-in module, the tourism module , the discovery module and spending within the App (maybe another specific report for this metrics), the KRE will distribute additional KRE grants to the top 20 Successful Apps (1M for the first App, 900k for the second...) in addition to the regular KRE

The extra KRE distribtion (appearance, modules deployment, spends, extra KIN if all modules are deployed) should be limited to 3 years, to incentivize Developers to join as quick as possible the Ecosystem and decreasing over time
During year 1, all the extra  entry KRE distributed should be 100%
During year 2, all the extra entry KRE distributed should be 80%
During year 3, all the extra entry KRE distributed should be 60%

**Comment by kikengineering** [comment]
Thanks for your feedback and idea.

It does seem like a good incentive to get more new developers building apps and being rewarded. We had some internal discussion about this though and are concerned it would be difficult to scale as more apps enter the ecoystem and as more modules are made by different developers in the community. The KF would need to go through and evaluate every app, or have a whitelisted set of modules. Both of these paths seem hard long-term.

**Comment by Polype01** [comment]
Sure but it is not like there are tons of App joining the Ecosystem at the moment. If you are understaffed, you could let some key users among community check and test the apps and see if the features are really setup and deployed. I understand the idea is to automate the KRE but it would be a KIN Reward to provide apps that try to deploy relevant modules.

You could limit these extra KIN grants up to the 300th App. It could be considered as an ongoing crypto challenge and open to the community.

**Comment by ipscan** [comment]
Thanks for the contribution. Perhaps this concept should be revisited on a case-by-case basis via grants, or some other means. Incentivizing the implementation of features is a great idea, but this may need to be separate from the KRE because there is no single "Kin Foundation SDK" with which to track this data on an ongoing basis and it would take away from the total KRE pool for developers, who would not be equally incentivized by fixed amounts of Kin. Leaving this issue open so that the discussion may continue.

**Comment by Polype01** [comment]
Well, I guess that you could be some screening programs that could check, scan and screen the code of the App for some key codes/commands and that would allow you to ‘recognize’ a deployed KIN module and count it for the KIN grant.
You can also ask the developers, when they submit their app to the ecosystem to tell you where the modules are located in the code of the app as a prerequisite.

**Comment by Polype01** [comment]
Oh and maybe you understood this already between the lines but there could also be a KRE for non kin developers :)

**Comment by hitwill** [comment]
Closed as discussion was concluded due to scale issues - with focus being on a case by case basis via grants.
