### ISSUE TITLE
Automated public KIN KRE report

### ISSUE THREAD

**Issue by Polype01** [kinecosystem/rewards-engine#28]
As the KRE is supposed to be transparent and automated, I would suggest KIN Foundation to take over and post the KIN KRE weekly Metrics that I have been posting on a weekly basis. Indeed, it would be nice to have that report automated and available to the Community and the partners.

For the moment, it is pretty straightforward and is just manual basic Excel with some simple formulas. Automating this report should not be too complex for someone with Programming skills imo

The input I use for the repot is the final KIN KRE posted every Friday-ish on the https://www.kin.org/kre/

I do not mind continuing doing this (FOR FREE and FOR FUN
[KIN KRE.xlsx](https://github.com/kinecosystem/rewards-engine/files/3888004/KIN.KRE.xlsx)
) but it takes 2 hours+ to make the file, to ensure that there are no errors (it is manual) and analyzing the data. Besides, on the long run, if more partners join the KIN Ecosystem, it will take even more time. Now it istill manageable.

Please find in attachment the file.

**Comment by asparagusm** [comment]
Just adding in,  I don't think this should be posted by staff to reddit.   We should be moving away from that. 

I agree this should data should be automated,  by a weekly update to a specific web page on the official site.  Add the ability to specifically  subscribe by e-mail to reward payout updates and those interested will get an automated e-mail with the latest data.  

Leave it up community members to discuss further on social media amongst themselves.

**Comment by Polype01** [comment]
good point asparagum-san.
I will ask the community about this point in the next KRE KIN stats report. Would be nice to have 1-2 extra users in backup to maintain it

**Comment by ipscan** [comment]
This issue has been raised to KF. Leaving issue open.

**Comment by ipscan** [comment]
Since Dec., KRE payout summaries are released publicly via Twitter in addition to going directly to developers. More ways of releasing metrics on KRE publicly are also being explored. Thanks for your contributions.
