### ISSUE TITLE
Total KRE reward should not depend on the dollar value

### ISSUE THREAD

**Issue by hitwill** [kinecosystem/rewards-engine#31]
If i'm not mistaken, the current KRE reward is based on Kin's value in USD. So if the value is lower, more Kin is rewarded to developers to help them cover costs. This probably works well on the short term, but also locks Kin in a vicious cycle. (Release more into circulation, to cover lower prices, which then lowers the price further).

Perhaps it should revert to the original declining curve, without adjustments?

**Comment by kikengineering** [comment]
The current KRE pays out based on a dollar value up to a payout cap (590,000,000 Kin/day for 2019 before considering the bonus/carryover pool). 
I.e. assuming there is no bonus pool, let's say the price of Kin is 0.000005 / USD. Then $0.09 USD / DAS -> 18000 Kin / DAS. Ignoring p2p and cross app, this means that if we have more than 590,000,000 / 18000 = 32777.8 DAS, developers will be paid less than $0.09 / DAS and instead be paid a proportionate chunk of the 590,000,000 payout.
Note that (as is the case now for 2019) there is a bonus pool remaining from earlier payouts which were not fully utilized there can be more than 590,000,000 paid out in a single day, but it will be used evenly throughout the rest of the year. Additionally, if the payout cap + bonus pool cap is met in a single day (which is starting to happen) then developers will again be paid out proportionately.
For 2020 there will be a similar daily cap which will come from the KF and hasn't been decided yet.

**Comment by ipscan** [comment]
Payout cap has been elaborated upon, which results in lower kin payouts than would go out otherwise. Issue closed.
