### ISSUE TITLE
Restore confidence(Not faith!) in investors, the KRE depends on the price, apps wouldn't go bust if the price didn't drop all the time

### ISSUE THREAD

**Issue by TheBubblePopped** [kinecosystem/rewards-engine#44]
Remove the buyback program. We've been told that Kin employees believe in the vision. If this is the case, then why don't you buy from exchanges by yourselves with your salary?

You get with the same money 40 times more than what you are paying in ICO terms.(You valued the coin is so much worth right Ted?)

1k yields 40k$ as an investment. But you don't,  the only thing in your mind is to get rich quick, without any risk at all(I mean your leader is a mastermind in doing this), that's why 19 people will receive a 25k * 40 = 10m investment for free on top of the salary. If the trend continues it will be more.

Why would anyone join the party if he knows that the top leaders abuse it 24/7.

Ted did his best to avoid responsibility, first not being the CEO but using 100m $, then saying he doesn't owe us anything and everyday there is new stuff coming out like yesterday when we found out the automoderating Kin Foundation subreddit bot isn't a bot but a human. 

The purpose of this human is to censor critics, moonshots are allowed just not critics, ask the right questions and you are out and you want to convince us that it's us who are crazy, but it's actually you being tyrants. This project has no signs of a crypto. It has a very vertical hierarchy, this is actually a centralized foundation run by Ted Livingston behind the scenes. His words don't match with his actions, either he is insane or he is deceiving like a true fraud. My bet is on the second claim.

If you had talked to developers instead of being apathetic we wouldn't lose partners and Developers wouldn't harass you behind your back. I got plenty of screenshots of various developers doing this. They are spitting on you and you think it's raining. It's the same answer all the time, they are taking the money from Kin but they are all ready to change ship. 

I am receiving screenshots every 1-2 weeks. Developers are afraid to talk freely about you, known names and not me and their instincts are right. TheRealChaseeB banned me from the discord for no reason at all, because he twisted the rules on his likings, that's why you are totalitarian frauds. 

Then, the cherry on the torte:
We have ted saying that those with the highest % or as  he said with "skin in the game" can judge and talk. But wait a minute. He gave us 4% for for 400b coins ~,
Kik owns 3Trillion coins without delivering anything. 19 Non Elite Kin employees will own(thanks to the buyback program) 1/4 the amount of investors who actually payed for it.

To fight a voice of a Kin Employee who didn't spent a dime on the coin he allegedly supports i would have to find thousands of investors. This is a tactic that even Russia couldn't come up to silence us. Putin is that you? 

Knowing that this one voice can be chaseeB makes everything just weirder since this guy is a totalitarian like most of the crew and nuts. Then you wonder why the price goes towards zero like martyrs and blame the SEC. You tell us to take responsibility with your totalitarian mods, how about you taking once in your life responsibility about the things you do, because it is clearly not the SECs fault. None of the complaints have to do anything with the SEC. 
 
There is no way this is ethical and this is still a very very mild expression. You are trying to delete/rewrite history on your Subreddit to alter the truth but people do not forget nor do they forgive. 

You can not collect 100m $ based on lies and expect that nobody will think you are accountable for it.

**Comment by WeviNest** [comment]
The psychotic ramblings of a gambler that lost big.

**Comment by TheBubblePopped** [comment]
> The psychotic ramblings of a gambler that lost big.

No not really, that's just a typical answer of a cult-member who is in denial that this project is not run by frauds. It's an answer of a cult member that is agreeing to buybacks because it will pump his bags, that's not me but you ;)

 What i say here is true regardless of the price of Kin. It will remain true even if it goes to 1000$/Kin

**Comment by ipscan** [comment]
This does not relate to the Kin Rewards Engine and will be closed. Please review rules for contrution.
