### ISSUE TITLE
Remove kinnies from KRE report

### ISSUE THREAD

**Issue by Polype01** [kinecosystem/rewards-engine#46]
Please round up/down the distributed KIN amounts from the KRE reports

**Comment by ipscan** [comment]
Thanks for your contribution. Payouts are now rounded to the nearest .01 Kin (e.g. 1,567,890.88 Kin), and payout summaries match these amounts. Do you find this to be acceptable?

**Comment by Polype01** [comment]
I meant that Kinnies are irrelevant (especially with the current KIN low valuation)
you can still round up/round down the KIN payout and get rid of those decimals.
Is there a reason why Kinnies should still be shown?

**Comment by ipscan** [comment]
Can you qualify your thoughts a little further? Why do you believe the decimals are irrelevant and what is your general analysis on the benefits of removing them? Thanks again

**Comment by Polype01** [comment]
1 KIN = 0.00000325€
1 KINNY = 0.0000000325€
The value of 1 KINNY is neglectable and is not that relevant value wise. 
The question would be why would you think it is relevant now. If you think it is, then please forget about this GitHub. 
It just adds more numbers to the numbers and does not add a real utility imho

**Comment by TheBubblePopped** [comment]
I am voting to keep them since this isn't a storage problem. We basically just lose accuracy with no benefit. Users can remove the last digits from the source if they want so in seconds.

**Comment by Polype01** [comment]
Accuracy is important but does it matter to know that KRE payouts amounts are 100000 KIN or 100000,08 KIN?

**Comment by TheBubblePopped** [comment]
Yes and no, i understand that it seems more like a philosophical question but why would you want to  spend time on fixing this particular problem while you know that the trade-off is losing accuracy?

Also it's a one way road. You can remove the decimal places from the source(SourceWIthDecimals -> ProcessedSource), but you can never add the decimals back(ProcessedSource->SourceWithDecimals). 

I also like the fact that decimals can be used as an identifier. Example:

KRE payout is 100000.15 Kin. No Txhash or anything like that mentioned at kin.org/kre so to find this transaction i would just query the blockchain and search for a transaction with the exact value of 100000.15 (not like this number can't occur several times, it's just less possible)

Without the 15 in the end it would be a pain in the ass to identify who this guy was. We could lose functions that we didn't even know existed.

**Comment by ipscan** [comment]
Thanks for the discussion. For the time being we have decided to side with accuracy and leave the flexibility of rounding up to anyone who cares to do so, as once we do so those who wish to know the minute details will not be able to revert the changes.
