### ISSUE TITLE
KRE Valid Transaction Guidelines 2.0

### ISSUE THREAD

**Issue by hitwill** [kinecosystem/rewards-engine#48]
**Section B:7.2 of KRE Valid Transaction Guidelines 2.0** [states:](https://github.com/kinecosystem/rewards-engine/blob/master/improvement-proposals/Valid%20KRE%20Transaction%20Guidelines%202.0.md)
If the amount of the Spend Transaction is equal to 1 KIN then the Transaction may be initiated by a single tap by the User (such as the User tapping 'like' or a 'heart', or tapping 'ok').

**Problem:**
The KRE v2 incentivizes developers to encourage [higher spending](https://github.com/kinecosystem/rewards-engine/blob/master/improvement-proposals/kik_kre_2_0.md#1-spend) for users.

**Tension between incentive and transaction guidleines:**
The problem here is that developers will start to incentivize higher spending, (raising the price of simple actions), but this will impact UX when a user has to click 'confirm' to spend bigger amounts on simple actions.

**Align incentives and transaction guidleines:**
To align the *incentives* to the *transaction guidleines*, the 1 KIN spend needs to be raised to 10 KIN, or 100 KIN. The user should be able to spend up to 100 KIN without clicking 'confirm'. One option is to require a confirm only once. (The first time the user spends 100 KIN, to let them know that each time they click e.g. the clap button, they spend 100 KIN. Once the user has confirmed once, they should not be required to confirm again.)

This would

1. Enable developers to incentivize higher spending
2. Give users a more pleasant UX, so they don't have to click 'confirm' repeatedly on smaller spends

**Comment by asparagusm** [comment]
Hi

These numbers came from the existing guidelines.

There's 3 options here:

Option 1 -  Leave it as it is.

Option 2 - Simple adjustment to the figures by increasing single tap Spends to transactions 'less than equal to 10 (or 100 KIN).'   

Option 3 -  We add a new provion between the existing two. E.g.  (1) 10 KIN or less can be a single tap,  (2) 10 - 100 KIN can be a single tap with a one time confirmation and (3) 101 KIN plus requires a confirmation.   Personally I don't think adding a one time confirmation does much for the UX experience, given the general requirement for spends that amount be visible so option 2 would be my pick.  I defer to the KF of course. 

It probably make sense we revisit this section at the same quarterly intervals that the DAS algorithm is reviewed.

**Comment by kikengineering** [comment]
Good catch @hitwill 
Option 2 seems quite reasonable (up to 100 Kin seems fine), but the amount for the single click transaction should probably be communicated if it's no longer 1 Kin. i.e. it seems a bit misleading to have a heart with a kin logo on it, but spend 100 Kin when you tap it. 7.3 a) could replace 7.1 a) to be a bit more specific and address this.
Revisiting this quarterly also seems like a good idea.

Also update: the KF plans to discuss and vote on the updated guidelines on Feb 6th (their next meeting).

**Comment by asparagusm** [comment]
Thanks. 

Sent you a pull request with an update.   Single tap spends are permitted provided the amount of transaction is less than or equal to 100KIN.  The paragraph has been caveated to firstly require the User be 'informed' of the cost of undertaking the action.  I've kept some flexibility here with examples that this can be a tutorial, confirmation or notification etc.    If we replace 7.1(a) with 7.3 then Apps like Imgvue would need to write '100 KIN' beside every like button,  I think there would be push back about that.  I think this more flexible approach is the right middle ground.

**Comment by ipscan** [comment]
Thank you for your contribution. This change was implemented by user asparagusm in his latest PR.
