### ISSUE TITLE
Need for updating spend guidelines 2.0

### ISSUE THREAD

**Issue by Throwawayburros** [kinecosystem/rewards-engine#54]
I guess I would like to bring up the [Valid Spend Guidelines 2.0](https://github.com/kinecosystem/rewards-engine/blob/master/accepted/valid-spend-guidelines-v2.0.md) because it seems it is still game-able in its current condition.

[This reddit comment](https://www.reddit.com/r/KinFoundation/comments/fcfd2a/are_ecosystem_participants_worth_more_than_you/fjabuyr) and [this one](https://www.reddit.com/r/KinFoundation/comments/fcfd2a/are_ecosystem_participants_worth_more_than_you/fjbfljq), cover it pretty well.  But in the event they get removed, i'll recap below.

I'd also like to note that my earlier concern with Rave has been addressed by Rave adding a log-in bonus of 1,000 Kin!

However, that does create a new concern. KRE 2.0 valid spend guidelines 12.1 says

> **You have credited a User an amount of KIN, only to force the User to pay all or part of the credited KIN back to you;**

I am on the fence here, but I think that giving 1,000 Kin on login and then 'forcing' the user to spend the 1,000 Kin to actually use the App (join a Rave) would qualify as a violation. A non-Kin app, Mario Kart Tour has a log-in bonus system just like Rave. The difference is in Mario Kart Tour you are rewarded Gold and/or Gems but you are not forced to spend them to play the game. This makes me believe that Rave is still in non-compliance.

In the Rave App, they give you 3 options upon successfully logging in.

1. View Settings (Costs 0 Kin)
2. View Friends List (Costs 0 Kin)
3. Join a Rave (Costs 1000 Kin)

Changing settings like language, is not the main draw of the app, so we can ignore that. Viewing the friends list, may be exciting for some, but the main purpose is to see who is online and then join a Rave with them. So that leaves #3, Joining a Rave as the primary function of the app. The only way to do that, is to instantly spend the 1,000 Kin they gave you for opening the app.

To recap, i'll make a timeline of a random users actions
- 01:00 RHLM39 opens Rave as a new user
- 01:01 RHLM39 earns 1,000 Kin for opening the app
- 01:02 RHLM39 spends 1,000 Kin for joining ThrowAwayYourKin's Rave
- 01:03 RHLM39 earned 1 Kin before exiting the Rave
- 01:04 RHLM39 is unable to join any Rave due to insufficient funds

Using the timeline above it appears that 01:01 is the earn and 01:02 is the forced spend.  I just dont see any other way how it can be viewed as anything but a violation.

I understand what they are searching for a way to maximize their KRE, but there has got to be a better way for them to handle this.  I would also encourage anybody seeing this to check the app themselves.  I also picked out a random user, and found the transactions that match the behavior I am describing.

[Random Users Wallet](https://kinexplorer.com/account/GBVAL6GEUS5VQYVKRLTWY2UTKHIHG3C656DLBPPEOW2BHSXFARML3LZH#payments)

[Login Reward on 3/2/2020 1:02 PM](https://kinexplorer.com/tx/c74672b06b7532820cffe8381e8a585c0d7332460cdc66afdccdd549c157afac)
["Forced" spend on 3/2/2020 1:03 PM](https://kinexplorer.com/tx/29bc6b93bde8aea2e0255b7798bdb93902bdeb173d8559765a8c90c405cb91e3)

[Login Reward on 2/21/2020 2:20 PM](https://kinexplorer.com/tx/17b3c018b69d2798a9ffbcfed893619d646f4b90cea73170e163c53958350d91)
["Forced" spend on 2/21/2020 2:21 PM](https://kinexplorer.com/tx/996f3f8bbfb62cd8e1ccd5bb65ac2a522b251dbf7b05f06633c7a753f7f024fd)

Obviously not all transactions match up to the history that I am providing, because there can be a delay between opening the app and making your first **forced** spend but every single user of the app gets the bonus and then instantly spends it, because they are forced to.  I understand the need for developers to offer a log-in bonus, like many apps do to drive repeat usage.  That is not my aim in this proposal to hinder that.  Quite the opposite actually.  My goal is to prevent apps like Rave from their abusive behavior and allow Devs to use log-in bonuses responsibly.  

So i'll use the arcade classic Pac-Man as an example.  Lets say we had Pac-Man as an app in the ecosystem.  When you open the Pac-Man app and its been longer than 20 hours since the last time you played, you would be rewarded with 100 Kin as your log-in bonus.  Pac-Man is free to play so play as much as you want.  However, you can pay 100 Kin to continue where you last died or play again for free at the very start.  I say that this is an acceptable usage and does not invoke 12.1 because it is not a forced spend.  The player can choose to continue and spend that 100 Kin or they can choose to start at the beginning. 

Last time Rave was in violation of the spend guidelines, the guidelines were modified to ensure fraud could not happen.  I just want to make sure that when and if a change happens to the spend guidelines, that we do not stifle creativity that devs may come up with, using the Pac-Man example above.

**Comment by kikengineering** [comment]
Thanks for chiming in, it's a difficult topic and we agree it is worth debate. This will be discussed by the KF within the next week but I would also like to state our stance:
We don't think that this is a violation of the current guidelines. This may be a poor user experience (this will be increasingly true as users start to view Kin as money) but ultimately if Rave wants to put the main functionality of the app behind a paywall, that is their own design decision: there are plenty of apps which cannot be used without paying.

**Comment by asparagusm** [comment]
Someone else has also posted on reddit regarding Kinfit not being in compliance with these guidelines too.
 
The guidelines are exactly that, a guide.  The guidelines themselves can't force a developer to follow them and if there isn't clear and timely oversight then it's reasonable to expect that developers won't follow them.  As I have commented previously elsewhere,  good transaction guidelines are only one piece in solving this issue across the ecosystem.

 The next step to solve this isnt necessarily revisiting the guidelines, it's actually building and defining the operating processes behind them.  This means defining how suspected violations are reported, then what happens immediately on receipt of that report, all the way through to a decision and resolution.

A key part of designing this process will be the concept of "natural justice".  This means to what extent the KF will invite the developer to participate in the decision process so the ultimate outcome is seen to be fair, consistent and free from bias.  

Without the internal operating mechanics, the guidelines will not operate in a governing and machine like fashion.

Happy to discuss this further if there's an opportunity.

**Comment by ipscan** [comment]
Thanks for your contributions. KRE violation & enforcement philosophy and recommendations have been an ongoing topic of discussion, this issue has been raised for further debate. Feel free to leave additional recommendations.

**Comment by ipscan** [comment]
Discussion has evolved to issue #58
