### ISSUE TITLE
One of the first steps to decentralizing the KRE payout process

### ISSUE THREAD

**Issue by Throwawayburros** [kinecosystem/rewards-engine#65]
This is based on [CommercialWishbones](https://www.reddit.com/r/KinFoundation/comments/g6ogo5/could_someone_who_understands_how_these_things/fod09r6/?utm_source=share&utm_medium=web2x) comments from Reddit.

**Simple Summary of motivation**

Right now, only the KF KRE team has access to the [Weekly KRE payment address](https://www.kin.org/blockchainAccount/?&dataType=public&header=accountID&id=GD2YFOMTV424PS3XKOF7IRAPHK36K4I3PGE6JNXA3OYYQTTX5X5CO5JN), which is considered to be held by a centralized custodian which is the Kin Foundation.  In the event of a catastrophic event (Biological, War, Financial, etc), the biggest draw to Kin is its Kin Rewards Engine and without the KF personal around to deliver them, Kin will fail and the legacy that employees and community built together will come to an end.  Its time to make sure that the Kin lives on regardless of what happens. But with a few small modifications, we can change this process from centralized to decentralized as envisioned by the whitepaper quote below.

Whitepaper page 6
> The Kin Rewards Engine will initially be administered by the Kin Foundation. However, over time, it will be decentralized based on smart contract technology....Ultimately, the Kin Foundation will facilitate the entire ecosystem’s transition to a fully decentralized and autonomous network.

To start, we should involve all of the KRE devs in the payout process through a decentralized method.  

**High Level Overview**

The Kin Foundation is running calculations on spends, earns, holds and more.  This also includes manual anti-spam measures. When that is done, they generate the payment amount that each KRE dev has earned for that week.  However, the payout portion should work similar to the governance of DAO-like structures.  I believe it should work in a similar fashion to [KyberDAO's governance](https://blog.kyber.network/kyberdao-staking-and-voting-overview-70be71ee58f0).  The quick version is, if you vote, you get rewarded.  In the KRE case, all devs who have an "app id" be required to vote on the record that the information provided by the KRE is accurate.  

Variant 1) Quorum - 51% or more devs must vote and approve _all payments_.  Failure to reach quorum means that weeks KRE payment to all devs is delayed until quorum occurs. 

Variant 1a) Pre selected quorum - 51% or more pre-approved devs must vote and approve _all payments_.  Failure to reach quorum means that weeks KRE payment to all devs is delayed until quorum occurs.  Every 30 days, a single new member will join the pre selected quorum.  As each new member joins, each existing member will have their voting percentage decrease proportionally.  To start this model off, the Kin Foundation will appoint 4 devs of their choosing the with the following voting power.
a) 40%
b) 20%
c) 20%
d) 20%
So that as little as 2 votes or as high as 3 votes will.  

Example - If the KF nominated KiK for the 40% as the expected voter who will vote weekly.  Then they would only need 1 additional vote from the community to ensure that the KRE gets delivered. 

Variant 2) Individual dev based - Each dev must vote and approve _their own payment_.  Any devs who do not vote within the timeframe allotted means that their KRE payment is forfeited.  Any excess goes into the KRE rollover pool.

Disputes - Currently KRE devs reach out to the KF for assistance to clear things up and that will continue to work that way.  This needs to be decentralized as well in a later PR.

**Methods to decentralize the voting process**
[Example of Decentralized Organization using Aragon voting on Ethereum](https://mainnet.aragon.org/#/governance.aragonproject.eth/0x277bfcf7c2e162cb1ac3e9ae228a3132a75f83d4/) - This is a fully featured product.  It would be perfect, however the ethereum gas costs, will make this prohibitively expensive unless someone enables meta-transactions.

Solana - smart contracts on the platform should allow for public voting and the cost for the KRE devs will be nominal for all involved.

Ethereum Ropsten Testnet - You may ask why I listed a testnet.  Well its simple.  Its public, you can get unlimited free ropsten ETH and as a result.. free smart contract transactions and free transfers for everybody! 
Just need to create an ERC20 called "KRE-V", which will be like USDC clone will be utilizing their Blacklist and Freeze features.  These two features prevents KRE devs who have been kicked out of the KRE from voting.  To vote, simply send 1 token to the voting contract or address to signify that they agree to the vote for that week.

[Aragon has a testnet on Rinkeby](https://rinkeby.aragon.org/#/), which is another ethereum testnet... so its fully featured and free.  Pretty easy to use interface.. did I mention its free?

I am not including Stellar Multi-sig because if a KRE dev had access and was removed through bad behavior, you wouldn't want them to still have access and vote.  It doesn't seem to scale well either.

Kin3 on-chain voting for the KRE.   The KF could create an address that nobody owns the private key to such as "GADDRESS2VOTEFORKREPAYOUTSVFMD4IKLXLSZV5YHO7VY74IWZILUTO" and then each KRE dev can send kin to the address to vote, either from their server wallet, KRE payout wallet, or hold wallet.  The amounts sent to the address would state their voting intent (0.00001 for yes, 0.0002 for no), or you could utilize the memo field instead.

**Comment by kikengineering** [comment]
Thanks for the detailed post. Working towards decentralization is extremely important. Operationally it definitely seems like more work for several parties involved, but that may turn out to be worth it.

We will discuss internally and provide our own thoughts and make sure this gets in front of the board by their next meeting (3 weeks from now).

**Comment by Throwawayburros** [comment]
A crypto VC fund called Placeholder.vc recently wrote an outstanding blogpost about Aragon for DAOs.  https://www.placeholder.vc/blog/2020/5/7/aragon-daos

According to Placeholder, creating a DAO with Aragon may allow the Kin Foundation to be compliant worldwide.

> You may be wondering about the legal boundaries of digital organizations. That conversation deserves its own essay. But fundamentally, a DAO is just a series of contracts between people just like paper organizations. So compliance should be up to its individual participants and the laws of their particular jurisdictions. But in principle, given the “unstoppability” of smart contracts, digital organizations are best considered as unlimited-liability flow-through entities [1, 2] meaning authorities should disregard the entity itself and instead “look through” to its members when allocating responsibility. In the end, each state will have to decide for themselves how to treat citizens who participate in DAOs and we should see a healthy dose of jurisdictional competition: if the transition is inevitable, states who embrace digital organizations early will benefit first.

**Comment by kikengineering** [comment]
Hey @Throwawayburros sorry for the delayed response.

We floated some of the  ideas you suggested to the KF at a high level (they are good ideas), but I don't think any action will be taken until either: you write a full-fledged proposal, or we work together to co-design one in a few months.

In terms of our thinking on decentralization, we are currently focussing on open-sourcing the KRE code (the logic is public, payouts always align to that logic, but we want to take the next step with the code portion). Once that is complete, we plan to start focussing on ways to further decentralize the process (including payouts like you've suggested). The will probably be late-summer, early fall.

**Comment by Throwawayburros** [comment]
> you write a full-fledged proposal, or we work together to co-design one in a few months.

Issue 65 is not a true KIP, and just an outline as I am unable to predict if we stayed on Stellar or Solana at the time of writing and more to gauge interest in the process. 
Almost 3 months later we still don't know if we are moving chains, but I will say that the tide seems to be changing in Solanas favor, and I'll mull this over and see if I can come up with something that works within the confines of Solana to be forward thinking.

**Comment by Throwawayburros** [comment]
[Now that we officially have notice that Solana is the new layer 1 chain for Kin](https://www.coindesk.com/kin-community-approves-move-from-stellar-fork-to-solanas-blockchain), it will be easier to propose a solution that fits.

**Comment by hitwill** [comment]
This is a really interesting proposal for longer term implementation. The KRE is still relatively young and needs occasional tweaks based on how the ecosystem reacts. However over time, as it matures and needs less and less manual watching, this avenue would be quite itneresting.
