### ISSUE TITLE
Kin Council Member Feedback [Valid Spend Guidelines 2.1]

### ISSUE THREAD

**Issue by KRicoyLL** [kinecosystem/rewards-engine#66]
Acting as liaison for feedback from reptar2015 of the Kin Council:

> My only question is, how does the council determine the outcome? I’m all for a majority vote occurring, but... I would believe even one member finding fault would be enough to further escalate the review.
> This takes the burden off of the council of having to meet up or having every member cast a vote.
Maybe we could do something along the lines of “after a single counsel member has reviewed the case, there will be a three day window in which a vote may occur to either pass the review forward or throw it out”.
> Just gives us a little bit of time to discuss it if necessary or review what our fellow counsel member has deemed appropriate.  I don’t see us stabbing each other in the back, but a little check and balance never hurt anyone.
> Maybe if it is decided by a counsel member to escalate and others object, we still send it to the KF with both arguments
> This may help the KF reach a decision quicker having both sides of an argument
Think of us as a jury, not the judge

**Comment by ipscan** [comment]
Feedback has been implemented.
