### ISSUE TITLE
Ideas to make the KRE more robust and trustless

### ISSUE THREAD

**Issue by l-hendriks** [kinecosystem/rewards-engine#68]
I was thinking for a while about the KRE and I have some thoughts that might be interesting. They are around making the KRE more robust and hard to cheat.

Basically, how eg Ethereum and Bitcoin prevent spam is by using transaction fees: they make it unprofitable to spam the network. The KRE entry barrier is very low and thus susceptible for gaming the system. Also, there is no time delay so you can just create a million wallets now, send 1000 kin to eachother and you have a million DAS while costing only transaction fees. So here’s some thoughts:

- Only count addresses towards the KRE that are older than 1 KRE period. So if a wallet is created within a KRE period, it does not count towards KRE earnings that period (eliminates quick spam AND adds incentive to create long term spenders instead of big one-off transactions)
- By default, wallet addresses DO NOT count towards the KRE. Creating an address is too cheap, but it should be (or free) otherwise big apps will not integrate as it is too expensive. However, to make an address eligible for KRE rewards, one should do a MAKE_ELIGIBLE transaction or something that registers the wallet as KRE eligible (using memo and saved in database by KRE engine). This should be expensive (like 100 Kin per address) AND BE TEMPORARY (like 100 Kin PER KRE PAYOUT PERIOD). The expected lifetime reward of that address is much higher than 100 Kin, but now making a million addresses by gaming the system costs 100 million Kin and is only valid for 1 payout period — this means that a spam attack has a (big) startup cost and a long reward delay (as you need to create the wallet, wait for 1 payout period and then make them eligible). One can start slow and add addresses to the KRE by using KRE rewards, so you slowly buy into more KRE, or you invest a lump sum to get everything immediately. You could turn this off for current partners or make it cheaper for whitelisted addresses.
- The 100 Kin spends go towards the KRE payout pool as a % increase of the normal KRE payout, so it is shared equally amongst the fair players (ie they get higher rewards, like miners and transaction fee while the normal KRE is like the block reward)
- Only count a spend if you spend it to the KRE address or another pre-approved wallet address if developers don’t want to use the KRE address (which you should not want) OF ANY APP, as well as other KRE ENABLED wallet addresses OF ANY APP. This incentivises tourism, disincentivises sending to exchanges etc. It still incentivises P2P spending, but first needs to have that big entry spend of 100 Kin to make it eligible. It also incentivises apps to expect high KRE rewards from wallet addresses, and again makes it hard to just send Kin around.

Basically it makes the entry cost of cheating the system very high, and by delaying the rewards, one needs to pre-fund with a lot of money to gain from it. As Kin gains in value, this becomes less and less attractive. One could also peg the MAKE_ELIGIBLE to a dollar amount ($0.01 per address or so, or whatever is on the low end of a KRE reward for 1 wallet) and update the amount of Kin it costs every KRE payout period, so the spam attack is always more expensive than worth the trouble.

In theory this could be a smart contract and fully decentralized (if the blockchain supports it), but this does not have to be the case in the beginning.

**Comment by kikengineering** [comment]
A few thoughts on these ideas (thanks for posting!)

Overall, totally in agreement that over time the KRE needs to be made more robost over time. There are definitely some potential vulnerabilities as you have described.

The first idea about disallowing newly created wallets: it would pressure developers to make retention-driven features which would be great. On the other side though, it would be a bit limiting in certain respects and stop developers from potentially engaging in certain use cases with lots of user/wallet turnover. We would need to get a lot of community buy-in before we went in this direction.

In terms of the second idea, at a high-level we think it's interesting and should be thought about and discussed. The amounts of Kin may need to be changed, and it may be a few months before this type of development needs to take place, but the idea makes a lot of sense.

**Comment by l-hendriks** [comment]
Thanks for the reply! Not saying these ideas are the right answer to the vulnerabilities, but the KRE is too important to not have continuous discussions about I think.

About the first idea (this is that wallets are KRE eligible after 1 KRE period right?): this was meant to delay a possible spam attack. A patient bad actor would feel no pain from this, so it's not the most important.

About the second idea (the MAKE_KRE_ELIGIBLE transaction you mean with this I guess?): I agree this is just a very very rough outline, just want to bring over the idea. I think a system like this is important for future of the KRE, but has to be integrated super carefully and tuned with the right numbers. Cool that it planted a seed, if you want to discuss more at some time let me know!
