### ISSUE TITLE
KIN KRE formula adjustment and extra grant to support "smaller" Apps

### ISSUE THREAD

**Issue by Polype01** [kinecosystem/rewards-engine#69]
The adjustment proposal consists of two parts
-	A) KIN KRE Periodic formula payout change
-	B) KIN KRE grant/bonus

**A)	KIN KRE Periodic formula payout change**

**Current Payout**
Across the three KRE tracks (Spend, Buy, Hold), a developer's (developer i) total payout is:
Payout_i = Payout_spend_i + Payout_buy_i + Payout_hold_i

**Payout Proposal review request**

This proposal is based on the KIN KRE data metrics gathered on www.kin.org/kre and the spreadsheet that I am updating each time a KIN KRE report is published.
https://1drv.ms/x/s!AkW5Dnexk07clnepjcoRZqV8-Xbm?e=JE5fMJ

Today by checking the periodic KIN KRE payouts, there is a huge difference in the payouts that are distributed among KIN Ecosystem Partners. 
Apps built and deployed by established corporate entities earn most of the KIN distributed by the KRE. Their development teams are big, experienced, professional and have a solid userbase already. 
The bigger Apps earn more and more KIN and the smaller Apps have less opportunities to receive a fair amount of the KIN KRE.
Within the KIN Ecosystem, the goal pf the KIN KRE is to reward all developers for their work and contribution but unfortunately, because of the structure of the current KIN KRE distribution model, the current distribution is unbalanced.
The KIN Ecosystem should be more balanced, inclusive, diverse and give a fairer chance to smaller Apps to thrive. I believe that smaller Apps or smaller developers teams should get a higher reward when they are joining the Ecosystem, but without impacting negatively the exisitng, successful Apps.

By checking the KIN KRE distributed during period Apr 12 – Apr 18, the top 10 Apps received 
3.229.733.438 / 3.400.429.767 = 94,98% of the period KRE
Based on this, it is very difficult for other smaller teams to get a decent percentage of the KIN KRE. (You may argue that they should be as successful as the established Apps or that it is not the big Apps’ fault if they are successful)

On the long run, we expect the value of KIN to increase based on the KIN Adoption, the increase of real and speculative demand. By then, it should be enough for smaller Apps to get more value from their contribution but unfortunately, we are not there yet. 
Most of the devs decide to sell a part of their valuable KIN KRE to the market to cover their operational costs (general Apps running costs, employees…) and because they do not have the choice.
Indie Developers/smaller teams who choose to build an App within the KIN Ecosystem are losing money, time and resource. They are also spending money and resources, maintaining their Ecosystem App. The current environment is not favorable to attract new Indie developers and consequently, the KIN Ecosystem has a natural entry barrier that makes bigger structures more likely to join. 

Hence, the proposal below of having a specific rate factor applied to the KIN KRE formula for a limited amount of time or, based on a first in approach, up till a certain critical number of Apps is reached (E.g. applicable to the first 200 Ecosystem Apps). The proposed rate factor could be also terminated when KIN price reaches a certain threshold for example

**Proposed payout**
The proposed KIN KRE adapted formula has the ambition to reward and redistribute better the smaller development teams who are currently building or who are willing to build an App within the Ecosystem :

****
***
Check I_Apps_NUM
If I_Apps_NUM < 199:
Then
Payout_i = (Payout_spend_i + Payout_buy_i + Payout_hold)* i_HUGE_RF + (Payout_spend_i + Payout_buy_i + Payout_hold)* i_BIG_RF + (Payout_spend_i + Payout_buy_i + Payout_hold)* i_MEDIUM_RF + (Payout_spend_i + Payout_buy_i + Payout_hold)* i_LOW_RF
Else
Payout_i = (Payout_spend_i + Payout_buy_i + Payout_hold)+ (Payout_spend).
****

Apps:
I_Apps_NUM = KIN Ecosystem App number
*Each Ecosystem App would get a specific integer number when they join.

Categories: 
Category Definition: An App is considered as
i_HUGE if 1B < KIN KRE distributed to the App 
i_BIG if 100M < KIN KRE distributed to the App < 1B 
i_MEDIUM if 1M < KIN KRE distributed to the App < 10M 
i_LOW if KIN KRE distributed to the App < 10M

*determining the number of KIN received by the App can be done by summing up all the KIN distributed by the KRE since its inception, without the specific additional grant/payments that are not periodic. The provided examples are based on the KIN distributed periodically via the KRE
**Else, specific additional grants/payments that were paid in extra can be taken into account but then, the number of Apps belonging to certain categories may vary. Some Apps that are considered as “Medium” can be considered as “big”
*** The determination of the size of an App needs to be clearly defined. 
a)	KIN that was ever distributed, periodically, by the KIN KRE.
b)	KIN that was ever distributed, periodically, by the KIN KRE + extra grants
c)	KIN that is stored on the primary wallet of an App

The following proposal is based on a), based on the KIN distributed periodically as publisehd on the official site

Categories rate factor definition: 
i_HUGE_RF = 1,003 (0,3%)
i_BIG_RF = 1,007 (0,7%)
i_MEDIUM_RF = 1,030 (1,03%)
i_LOW_RF = 1,060 (1,06%)

*The idea is to determine and apply a rate factor to the current KRE 2.0 formula in order to give a slightly increased amount to smaller/medium sized Apps
** Huge Apps will also be part of that KRE adjustment because all Ecosystem Apps must benefit any KIN KRE formula adaptation.

**Validity:**
* Valid up till the 200th App to join the KIN Ecosystem and/or till a specific moment in time. 
** Setting up a validity end date ensures that the extra increase of KRE amount would be limited in time and would not cause a big increase of the inflation.
*** Setting up an end date could trigger a FOMO movement among developers to join the Ecosystem asap in order to benefit the extra KIN earned from the rate factor

**Example As-Is**
By checking the KIN KRE data from Apr 12 – Apr 18, the following amounts have been distributed to the KIN Ecosystem Apps (3.400.429.767 KIN total):
I_HUGE = 12 Apps = 3.229.733.438 KIN (Incl. Psiphon and Vent) – 94,98% of period KRE
I_BIG = 7 Apps = 143.033.727 KIN – ,4,21% of period KRE
I_MEDIUM = 26 Apps = 27.658.678 KIN – 0,81% of period KRE
I_LOW = 35 Apps = 3.924 KIN – 0,00%  of period KRE
Total: 3.400.429.767 KIN 

**Example To-Be**
After the adjustment with the proposed rate factor, it would be like: 
I_HUGE = 12 Apps = 3.229.733.438 KIN (Incl. Psiphon and Vent) * 1,003 = 3.239.422.638 KIN
I_BIG = 7 Apps = 143.033.727 KIN * 1,007 = 144.034.963 KIN
I_MEDIUM = 26 Apps = 27.658.678 KIN * 1,030 = 28.488.438 KIN
I_LOW = 35 Apps = 3.924 KIN * 1,060 = 4.159 KIN
Total: 3.411.950.198 KIN

The adjusted KIN KRE 3.411.950.198 KIN would be an increase of 0,338% compared to the KIN KRE distributed in Apr 12 – Apr 18 period (3.400.429.767 KIN)
The net extra delta per period would be 3.411.950.198 - 3.400.429.767 = 11.520.431 KIN
So roughly, for 52 period and for 80 partners = 599.062.412 KIN

**B)	KIN KRE grant/bonus**

On top of this periodic KIN KRE formula adjustment, I would propose the following 
KIN KRE bonus incentive to existing Ecosystem Apps
A snapshot of the KIN Ecosystem App could be taken on XX/XX/2020 (date to choose), the Kin Foundation could retroactively grant a fixed KIN KRE bonus to Ecosystem Apps depending on the category (LOW, MEDIUM, BIG, HUGE) where they belong:

HUGE = KIN KRE grant distributed to the App = 30.000 KIN
BIG = KIN KRE grant distributed to the App = 70.000 KIN
MEDIUM = KIN KRE grant distributed to the App = 300.000 KIN
LOW = KIN KRE grant distributed to the App = 600.000 KIN

By checking the KIN KRE data from Apr 12 – Apr 18, the situation would be the following:
HUGE = 12 Apps = 30.000 x 12 = 360.000 KIN
BIG = 7 Apps = 70.000 x 7 = 490.000 KIN
MEDIUM = 26 Apps = 300.000 x 28 = 8.400.000 KIN
LOW = 35 Apps = 600.000 x 33 = 19.800.000 KIN
Bonus total: 29.050.000 KIN

As a prerequisite, a mail can be sent to the developers of these Apps with a deadline date DD/MM/2020 HH:MM to see if they would accept that bonus.
If they respond by DD/MM/2020 HH:MM, it means that they agree to this bonus and they will receive it at another determined date
If they do not respond by DD/MM/2020 HH:MM, it means that they do not agree to this bonus and they will not receive it. (This is also a indirect way to check if the App Dev team is still active or not)

The purpose of this extra grant is to help the existing smaller active Apps to thrive and to motivate the developers to continue their journey within the KIN Ecosystem. Maybe that extra grant will not revive all the smaller Apps but it could be worth the shot and it would give the signal that all Ecosystem Apps matter.

That extra boost in KIN via the KRE could benefit doubly to the smaller Apps. 
By keeping the KIN on their wallet, they would be eligible to the HOLD section of thecurrent KIN KRE

**Comment by kikengineering** [comment]
Hi Polype01,

Thanks for the idea. At a high level, we understand the premise: it is essentially a redistribution of wealth from the bigger to smaller players in the ecosystem. We were wondering if you could give a bit more insight into why you think this redistribution is in the long term best-interest of the ecosystem as a whole? For example, this could go much further and redistribute more of the top apps to smaller players. Is this Kin amount enough to engage the small players?

**Comment by Polype01** [comment]
Hello,

>  At a high level, we understand the premise: it is essentially a redistribution of wealth from the bigger to smaller players in the ecosystem. 

Indeed, it is a better redistribution of the wealth, a proposal to have a more balanced redistribution of the KIN KRE that will motivate and incentivize more smaller devs to develop on the KIN Blockchain and to ensure that they will not work too much at a loss at the beginning. 

> We were wondering if you could give a bit more insight into why you think this redistribution is in the long term best-interest of the ecosystem as a whole? For example, this could go much further and redistribute more of the top apps to smaller players. Is this Kin amount enough to engage the small players?

This is almost a political/philosophical topic and the vision that you guys have on the Ecosystem.
What do you want the Ecosystem to be later on? How do you see it state in 5 years? An ecosystem only composed of mid/big entities? Do you want the Ecosystem to include only oligopolies of partners ?

The KIN KRE is supposed to reward all developers for their contribution within the Ecosystem. Factually, by checking and analyzing the KIN KRE distribution on a weekly basis since 1 year, I see more and more the trend that Top Apps earn more and more KIN (the big gets bigger) and the smaller Apps diseappear completely. For the period Apr 19 -Apr 25, only 32 Apps received KIN from the KRE, which is 40% of all Ecosystem Apps. I do not see the trend changing if nothing changes. 
The picture of the Ecosystem I have is an Ecosystem that does not welcome smaller dev teams. It is as I said a natural barrier. In order to enter the Ecosystem, an Indie dev team/smaller dev team has to lose money unless they get a grant in KIN or Fiat at entry or a better part of the KRE periodically, depending on the amount of KIN they have ever received. 

I understand that you have to deserve the KIN based on your app activity but if the current situation will not change, developers will not join unless they invest heavily on an App, meaning that they have already funds and existing user base. My proposal will not ensure that smaller teams continue their activity (some Apps might just want stop their activity and we cannot get them back) but I am sure that giving more to the smaller teams will give them the boost and motivation to continue their KIN journey longer.

Does the KIN Foundation want to foster creativity and attract many smaller dev teams or Does the KIN Foundation want to attract only professional mid/big size Apps ? You would increase heavily the adoption and use of KIN by Devs if it is interesting value wise and if they would get more than the bigger partners at the beginning. From an economic standpoint, most of the GDP does not come from big multinationals but from smaller business entities.

So that is my way of thinking. Not communism but KIN Socialism ;)
Supporting the little devs at the beginning by giving them more KIN via the KRE and if they are successful later, they would get less KIN.

I believe in an open Ecosystem, where anyone can contribute by creating an app and deploying the KIN App modules and get going.
I would like to see the KIN Ecosystem to host the next "flappy birds" indie dev end become successful.
The extra KIN distributed to the smaller dev teams is not a tremendous increase of KIN supply and I think that it is not a huge exaggerated request (I am not a KIN developer by the way and have no personal interest in this)

Kind regards

**Comment by Polype01** [comment]
"The Kin Foundation’s purpose is to support an **open**, decentralized ecosystem of
digital services; establishing a **fair**, transparent and accountable Ecosystem governance
regime which secures the Ecosystem against economic vulnerabilities, manipulation and
other risks to the credibility, reliability and use of the Ecosystem; **providing support** and
funding for the research and development of innovative technologies, applications and
services offered in the Ecosystem; **fostering and incentivizing an environment of
innovation** among participants within the Ecosystem; and collaborating with academic,
business and community partners to enhance the Ecosystem"

https://messari.io/pdf/kin-foundation-transparency-report-2020-05-20.pdf

**Comment by l-hendriks** [comment]
I disagree with this, it would disincentivize bigger apps to join and I think it's not fair for big apps that have spent countless hours and cash in order to get big and then get penalized for being to big. I don't think you should look at the % of KRE profits, of course if I have an app with a million users I will get 10.000x the revenue vs if I only have 100. You literally have 10.000x the amount of users.

All earnings in apps (advertisement, in-app purchases, etc) are always counted as CPA or eCPM or something: earnings per (1000) users.

Also, the KRE is not set up as "there is X kin to distribute and it will be distributed amongst apps as a weighted sum of the daily active spenders". Rather, it is set up as "you get paid X Kin per spender", with tiers of how many a person spends. You can calculate **your** KRE profits independently from other apps, as how it should be.

Actually, according to the document, you get $0.15 per 1.000 Kin spender. So if you have 1 user that spends 1000 Kin, you get $0.15. If you have 1000 daily users that on average spend 1000 Kin, that is an eCPM of $150. **This is really good!** Way, way more than for example average eCPM of $5 or so per 1000 ads watched.

As a small app, you get 30x more money per 1000 Kin spender, then when they watch an ad for gems. Let them watch an ad for Kin, get 1000 Kin and let them spend that on an in-game item or so, and get $155 eCPM in total instead of $5 if you don't have Kin.

**Comment by Polype01** [comment]
Hi Luc,

Thanks for your opinion on this.

My proposal, if accepted, would not penalize bigger successful Apps as they would also get a percentage increase of KIN. The idea is to make the smaller Apps earn a bit more KIN from the KRE, especially in the beginning, in order to mitigate their costs. Smaller teams do not have economies of scale that the bigger Apps have. The extra amount that I calculated would not make a dramatic change in the KIN KRE distribution but it would be a slight adjustment.

From I read, you are more in favor of an Ecosystem that is more professional and mid/big size oriented, which is fine. We need powerhouses and killer Apps to get more visibility and adoption but in my opinion, the Ecosystem would gain by fostering and allowing more easily any Developper to join and develop within the Ecosystem. I believe that the more people joining the Ecosystem, the more creative and richer it becomes.

I believe, as the current KIN price is not high enough for the moment, that many developers would choose other established blockchains to develop Apps. If it is costly and difficult to join the KIN Ecosystem for any random developer, they will go elsewhere and it will be a missed opportunity.
Do we want to attract new Dev teams only through KIN developments contests?

Again, it depends in the vision of the KIN Ecosystem on the mid term. Do we want an Ecosystem open for all developers or an Ecosystem mostly for professional developers working already in an existing working structure? 

Regarding the user base, it is an unfair comparison. You cannot compare a userbase of Madlipz with the userbase of a smaller App. An indie developer, would certainly not have a lot of users at the beginning (unless you market your App a bit beforehand which is costly in time and money and even with this done, I ma not sure it would be sufficient) and as an amateur developer, the revenues in the first months will be little to non existent. If an App has a solid team, and knowledge and an existing user base, they would earn a lot of KIN on week 1 from the KIN KRE 2.0. 

Your reasoning regarding the KIN Ads is correct of course but I think that if a random developer will build an App from scratch, it will take months to have some userbase and some visibility and success before even having some KIN from the KIN Ads. By then, the developers would have already stopped maintaining their Apps because of the cost.

Look at the KIN KRE 2.0 distribution breakdown. There are probably Apps that are inactive for many reasons: developers stopping their activity for any reason, bad App, unpopular App...but I think that a lot of those Apps which looked promising, are not active anymore because they became too costly to operate. 

My proposal would allow to give more KIN to the new Apps at the beginning of their existence, to give them a bit more time to get things going. It is an incentive.

Eventually, after some months, when the Apps become successful, they would receive a bit less KIN from the KRE and that KIN would be redistribute to small newjoiners.

Kr,

**Comment by l-hendriks** [comment]
Hi,

Thanks for the elaborate response! Not sure I came off hard, that wasn't the tone of the message, just want to spur some discussion :)

What you're saying it of course true, but if you do anything (build an app, start a lemonade stand) you earn nothing in the beginning. Having a way to get $150 earning per 1000 interactions is already huge and like 30x market average (altough you cannot compare spenders to ad watchers, but  you get the point). So my question to you is what is enough? What do you think a $ per 1000 interactions is fair for a small app? If you're small and get a 6% increase, then you go from $150/spender to $159/spender. Will that make a big difference? Will 10 million Kin, $70, bring back lost apps?
I think in the early days you don't want higher earnings per user (because $150 or $1000 times 0 is still 0), but that's where the grants are (were) for: the 2nd developer program for example paid 100 million Kin to integrating apps, which is a very good start and a deal you get basically nowhere else. In my opinion, the KRE is already better than anything out there for indie devs.

Sidenote, the KRE earnings is independent of the Kin price, as the KRE is set to be ~$0.15 per 1000 Kin spender. Just sell the KRE if you need the money.

And about Kin Ads: ignore the earnings from ads. People earn Kin from watching ads (say 1000 per ad) and then spend it in your app (given you have good spends) and you get $0.15 per ad watched + spend combination (and some ad revenue).

I think why apps struggle is mostly because of motivation. Creating an app or web app or something is super hard and not to be underestimated. You are happy with your first version and then the users come in complaining about everything (ugly, bugs, whatever). You have spent 100s of hours into making something just to be criticised which is super annoying. Then you have to plow through but most quit. This is not just Kin, 90% of all startups fail, and I don't think giving a bit (or a lot) more money will solve it.

Also: if you distribute more Kin using the KRE, you have to take into account an increased inflation rate and sell pressure which will drive down the price of Kin for everyone. The benefits should outweigh this (haven't thought about it, just wanted to mention).

Cheers!

**Comment by Polype01** [comment]
Hi Luc,

Hey no problem, did not feel it was harsh at all. No worries

To sum it up. What will drive and incentivize people to develop more is value.

The time spend, the promise of future value throught the KRE will make people and companies join the Ecosystem. 

There is a place for any participant to me and the Ecosystem should be more open. We currently have 30 Apps/80 that are receiving KIN through the KRE. Why do the bottom 50 Apps are not active anymore?

A) bad Apps -> OK, they deserve to die :D
B) Dev have no time anymore -> pity
C) Devs wanted just to give it a try -> not serious or focused enough -> OK they will fade away
D) Devs who really want to develop an App but find the time/effort spent greater than the maintenance/upgrade/operating cost  -> those people are the ones I would like to see helped and favorized, protected, supported by the KRE. If those guys or teams can earn more KIN initially and up till a certain threshold, then I am sure the retention rate (or activity rate) would be much higher

30 Apps/80 is not much for the moment...

I would even give MUCH MORE to the smaller projects that are really serious but we have to please everyone and also the bigger partners. I am not against bigger successful Apps (they deserve their KIN) but I do think everyone could get a bigger piece of the KRE cake

It is what it is but comparing and making compete a professional App like Madlipz and another indie App X is not fair and in order to foster more diversity and more people to join, an increase of KIN should be implemented for smaller devs/teams

**Comment by l-hendriks** [comment]
Hi Polype01,

Thanks for the explanation! I see your point, I also learned recently that the amout per Kin is a maximum that is only reached when the sum of pending payouts is less than the KRE budget. For example if there are 1.000 users that spend 1 Kin in the ecosystem, 3 million Kin should be payed out. However if for example the budget is only 1 million Kin, the amount of Kin earned drops by a factor 3 (I call this now the penalty factor for later in the post) so every spender is worth only 1000 Kin instead of 3000.

This would mean that the Kin per spender for small apps is penalized also if there are very big apps that make the ecosystem go "over budget". That is a point that I see that might be a bit "unfair", as the smaller apps get less Kin _per spender_ (additionally to getting less Kin because of less amount of spenders, which is fair) because the big apps have a lot of spenders.

It could be made such that this penalty factor is dependent on the % you contribute to the ecosystem. So bigger apps might have a factor 4 and the smaller apps a factor of 2 for example. Is this what your proposal contributes to?

Thanks!

**Comment by Polype01** [comment]
Hello Luc,

I was not aware of the repartition logic regarding the budget.
So indeed, based on what you have just explained, I feel more confident that something has to be adjusted for smaller Apps. There is a small systemic flaw regarding the distribution and the penalty that is impacting more smaller Apps strengthens the need of slightly rebalancing the KRE payments  in favor of those smaller Apps.

I proposed to have a percentage adjustment based on the KIN ever distributed to the App to try to balance the payoffs distributed. This is a rough proposal and it has the advantage of not increasing tremendously the supply. I believe that if more KIN are distributed to smaller Apps, the more it will attract Developers.

i_HUGE_RF = 1,003 (0,3%)
i_BIG_RF = 1,007 (0,7%)
i_MEDIUM_RF = 1,030 (1,03%)
i_LOW_RF = 1,060 (1,06%)

Example As-Is
By checking the KIN KRE data from Apr 12 – Apr 18, the following amounts have been distributed to the KIN Ecosystem Apps (3.400.429.767 KIN total):
I_HUGE = 12 Apps = 3.229.733.438 KIN (Incl. Psiphon and Vent) – 94,98% of period KRE
I_BIG = 7 Apps = 143.033.727 KIN – ,4,21% of period KRE
I_MEDIUM = 26 Apps = 27.658.678 KIN – 0,81% of period KRE
I_LOW = 35 Apps = 3.924 KIN – 0,00% of period KRE
Total: 3.400.429.767 KIN

Example To-Be
After the adjustment with the proposed rate factor, it would be like:
I_HUGE = 12 Apps = 3.229.733.438 KIN (Incl. Psiphon and Vent) * 1,003 = 3.239.422.638 KIN
I_BIG = 7 Apps = 143.033.727 KIN * 1,007 = 144.034.963 KIN
I_MEDIUM = 26 Apps = 27.658.678 KIN * 1,030 = 28.488.438 KIN
I_LOW = 35 Apps = 3.924 KIN * 1,060 = 4.159 KIN
Total: 3.411.950.198 KIN

So not that a big of an increase of supply, all things being equal and maybe not a significant increase for the small apps but that's why I come up with a one-time, one-shot bonus and I see that you did not provide an opinion on that section.

I think it could still be nice to provide some extra incentives to those small Apps as a gesture of support. That bonus could be also linked to some conditions (deploying all KIN modules in-Apps such as KIN transfer, providing spends, earns...) and/or performing the needed adjustments to be deployed on the Solana blockchain

**Comment by hitwill** [comment]
Closed as we switched to rewarding AUB which gives smaller apps a more even playing field. However, adjustments to the monopoly cap are also worth considering.
