### ISSUE TITLE
Use fees to prevent gaming and support token value

### ISSUE THREAD

**Issue by halfsharkhalfaligator** [kinecosystem/rewards-engine#7]
The fairest way of calculating a services contribution to the community is using the total value of transactions rather than the total wallet value. Gaming could be eliminated by the introduction of a fee (e.g. 0.1% of all transactions are burnt).

The introduction of a transaction fee should have additional benefits. In a recent blog post Vitalik Buterin described the importance of medium-of-exchange tokens having 'sinks' (places where tokens actually disappear such that the token quantity decreases over time) to prevent collapses in value:

http://vitalik.ca/general/2017/10/17/moe.html

Whereas I do not have the expertise to comment on the validity of Vitalik's post, introducting a 'sink' such as a transaction fee seems like the simplest way of preventing spam (Ripple has fees for this reason) and gaming and supporting token value.

Reducing the quantity of available tokens through fees is equivalent to providing interest to token holders such as 'capitalists' and the Kin foundation. It should therefore be popular with everyone currently invested in the ecosystem.

[edit: Whereas Ripple uses a fixed fee, a percentage fee would be required to prevent gaming. This fee would only be necessary for transactions taking place within Kin foundation approved services. Transfer of tokens between normal users would not have to be subject to fees.]

**Comment by sumthinknew** [comment]
This. Absolutely. This addresses multiple issues. I really hope this will be seriously considered (and implemented).

**Comment by lbeder** [comment]
This is a great suggestion. Thanks!

**Comment by odednoam** [comment]
Thanks @halfsharkhalfaligator, very insightful!

I agree it makes sense to use fees to some extent, either on their own (as you suggest) or a mixture of fees and inflation. We need to make sure the transaction layer we choose can support collecting fees in such way. (which may not happen until it has full support for smart contracts, but we can start planning for it now). 

I put it on my task list, and will will post more info about this analysis as we progress with it.
