### ISSUE TITLE
Proposed alteration to the KERE

### ISSUE THREAD

**Issue by ghost** [kinecosystem/rewards-engine#73]
If approved Kin will be moving to Solana by Jan 2021 and with Solana integrating with Chainlink it provides the mechanism to exchange Kin for any other cryptocurrency integrated with Chainlink. The problem with mechanisms like this (Dex) is they require liquidity pools so my alteration would be to change the KERE to the KLRE (Kin liquidity Reward Engine) where instead of paying centralised exchanges instead individuals are paid to provide market making/liquidity for decentralised or even centralised exchanges. 

Currently the proposal is for a USD value of about $6000/week at the current price or about $96,000 at ICO price. The likes of Solana are paying out $250/week to liquidity miners through Hummingbot leaving plenty of room for Kin to be the go to cryptocurrency for market makers to earn a passive income.

The KLRE will:
- help provide market stability.
- grant the opportunity for current Kin holders to be part of a staking like mechanism.
- tie up Kin in market making bots.
- remove the need for market making to be part of the KF budget.
- still encourage exchanges to list Kin so they can get those exchange fees.
- get the Kin in to the hands of more people rather than be given to a select few.

**Comment by ipscan** [comment]
Thanks for your contribution. This issue is being investigated along with the KERE proposal.
