### ISSUE TITLE
KRE Transaction Guidelines update - Buy Track Modules 

### ISSUE THREAD

**Issue by asparagusm** [kinecosystem/rewards-engine#74]
In anticipation of modules being developed in connection with the buy track KRE rewards, my proposal is to update the KRE Transaction Guidelines to set some basic standards for all modules. I have submitted a pull request incorporating the below.  

The changes are:

New definition 

| "***Module***" | a whitelisted module which purchases KIN from external markets;  |

 New requirements

**Module Requirements**

-  A User must voluntarily initiate a Module, which by way of example may occur by watching an advertisement, filling out a survey or being prompted to purchase KIN with fiat currency.  

- The amount of KIN sent to a User by use of the Module must not exceed the amount of KIN sent to the Developer from the creator of the Module.

- The total aggregate KIN sent to a User in connection with its use of the Module must not exceed the ratio of $1 to 3 KIN, based on the prevailing market rate of KIN at the time of payment.   (Example: A user can earn at most $0.03 worth of Kin for an ad generating $0.01 of revenue).

- Modules cannot be duplicated within an Application.

-  A User cannot initiate multiple Modules by a single action.  

In addition, the pull request includes basic tidy ups to the guidelines and includes a background section (the guidelines previously had a place holder to incorporate a medium article one day so that's been removed/updated).

**Comment by asparagusm** [comment]
Some thoughts on this:

-  if the developer is ultimately paying 4x or 5x of the market rate to users, then their entire KRE payment is at risk of being suspended.

-  if this issue arises due to the module paying this rate to the developer, then the module may be removed from the whitelist.  Although, I'm not sure how this arises - if the module revenue is purchasing KIN on the open markets at the "market rate"  the ratio is 1x.  Where does this surplus KIN come from to get 3x the market rate, isn't it the developers own wallet supplementing the module revenue?  

-  In any event,  if we add some words that surplus KIN exceeding 3x market rate will be ignored, is that actually possible to audit and adjust downwards given for any given app there may be hundreds of transactions for the relevant payment period?  Isn't it better to maintain a strict compliance policy both at the developer and module level - "comply or die"?

**Comment by kikengineering** [comment]
So you're saying:
- If a module breaks the rules (after being whitelisted) and the developer does not realize this and pays Kin to users that is outside of the allowable bounds, the developer could lose KRE payouts. Maybe this is a fine default decision, but it feels not great. It probably isn't a huge deal and is unlikely to happen.
- The other case that seems more realistic and concerning is if a developer makes their own module for their own use, gets it whitelisted and uses it to pay developers more than the 3x market rate to game the system. In this case it 100% makes sense that a developer does not get their KRE payouts, if they were abusing the module in order to do so.

At any rate, after rereading what you wrote and thinking about it, it seems like what you have suggested is sufficient. Optionally, we could add a line or two stating that if a module creator is using the module to obviously game the KRE for their own app's gain there could be stricter penalties, but maybe that's not needed.

**Comment by asparagusm** [comment]
I think this is not a big deal and what you're suggesting is a different approach we have taken to the rest of the guidelines.

There's a couple of avenues here:

1.  We can take the view that once these guidelines are set, it's up to the KCC to apply them and exercise their discretion if the issue was not the primary fault of the developer.   That follows the discretionary approach they take with all other breaches of these guidelines - including the ability to remedy breaches.

2.  OR, I can add a sentence to the end of this clause that says something like the "...payments from the KRE to the developer in respect of a Module may be reduced if the developer breached this clause solely because of a technical issue with the relevant Module not within the Developer's control and the KCC have determined that the technical issue can be resolved in a reasonable period of time".  I suggest it would increase the burden on the KCC and KF to figure out what's reasonable in the circumstances which may be difficult to calculate - especially if a Module is paying say 50x the market rate,  we couldn't just ignore that in calculating their buy-track payment. Do you agree?  

Personally I prefer (1) but happy to go with what you want.

Again i'm not sure how this issue arises though as mentioned earlier, because it wont be sustainable for a module to pay 3x the market rate long term.

**Comment by asparagusm** [comment]
- Removed Awareness/Control requirement - replaced with a description of what constitutes a voluntary transaction by a User.

- Updated Buy Module section based on discussion. Have made it clear that the responsibility is on the developers to ensure if they are integrating a Module that it meets the 1:3 ratio requirement.
Developers cannot pay more to Users then they receive by the Module (however they can pay less).   

- Updated KRE Violation Procedure -  Our recent changes to this procedure were not included, subsequently we also discussed a fast track process.  Rather than duplicate the steps and decision making process - it now just refers the reader to the decision making procedure document we created.

- Removed Prohibited Transactions Sections - given all Spend Transactions now have strict requirements to be voluntary - it feels redundant to me. A series of manufactured spends cannot happen if the spend transactions in the series are truly voluntary.  This puts greater emphasis on the User experience.  

Look forward to your thoughts on this - see pull request edits for exact changes.

**Comment by kikengineering** [comment]
Great overall, few comments.
- 10.3 has a typo:
does not reward KIN at a ratio that exceeds the ratio of _$1 to 3 KIN_ (should be $:$ or Kin:Kin)
- Overall, we're not sure if 10.3 should be the developer's responsibility. As long as the developer follows 10.2, it seems like 10.3 should be the responsibility of the Module Developer. Perhaps we could add a sentence that if the module and app developer are the same entity, then the developer's payouts would be impacted by not following 10.3. The last sentence is a good addition though.

**Comment by asparagusm** [comment]
What about this to replace 10.3:

If the Developer can edit the Module code or is involved in the Module's development, then the Developer must ensure that each operation of the Module does not reward KIN at a rate greater than 3.00x the revenue generated (Example: A Module can pay at most $0.03 worth of Kin for an ad generating $0.01 of revenue).  While Modules are tested at the time of being whitelisted,  Developers must report Modules which are not compliant.

**Comment by kikengineering** [comment]
That looks great 👍

**Comment by asparagusm** [comment]
Great, updated and done/

**Comment by hitwill** [comment]
Closed as it completed to resolution, including updating transaction guidelines.
