### ISSUE TITLE
KIN KRE 2.X - adjustments proposals to the spend/hold/buy tracks

### ISSUE THREAD

**Issue by Polype01** [kinecosystem/rewards-engine#76]
**KIN KRE algorithm adjustment proposals**

KIN 2.0 formula (current)
Payout_i = Payout_spend_i + Payout_hold_i + Payout_buy_i 

**1.	SPEND PART**

Proposed KIN KRE formula adaptation (adjustment of Spend part)
Payout_spend_i = [(Payout_spend_i*60%] + [Payout_spend_i*40%]
Payout_spend_v = Payout_spend_i*40%
Payout_spend_f = Payout_spend_i*60%
Payout_spend_i  = Payout_spend_f + Payout_spend_v

Adapting the KIN KRE payout formula (Payout_spend_i) by considering the quantity and variety of spends opportunities in an Ecosystem App 

•	The total payout_spend_i determination will be multiplied by 60%, which becomes the **fixed part** of Payout related to spends for an App. The fixed part is payout_spent_f

•	The total payout_spend_i determination will be multiplied by 40%, which becomes the **variable part** of Payout related to spends for an App. The variable part is Payout_spend_v

The intent is to incentivize the Apps to propose and deploy a higher number of spends in their Apps. The more spends they would propose to the users, the more KIN they can get from the variable part Payout_spend_v. Payout_spend_f becomes the fixed part of the spend part.

If implemented, the refining of Payout_spend_i will lead to a reduction of supply as most of the Apps do not currently have 21+ spends. It is up to them to optimize their Spend section of the KIN KRE by increasing the number of valid and relevant spends in their Apps. 

This change, if accepted, would need to be announced upfront to all Ecosystem users so they have time to adjust their spends.

**Payout_spend_v determination**

0 spends =  Payout_spend_i = 0 
1 to 5 different spend options =    Payout_spend_v = [(Payout_spend_i*5%]
6 to 10 different spends options = Payout_spend_v = [(Payout_spend_i*10%]
11 to 15 different spend options = Payout_spend_v = [(Payout_spend_i*20%]
16 to 20 spend options = Payout_spend_v = [(Payout_spend_i*30%]
21 spends or more =  Payout_spend_v = [(Payout_spend_i*40%]

**Example1: KIN KRE 2.0 current payout**
Payout_i = Payout_spend_i + Payout_hold_i + Payout_buy_i 
1M KIN = 600.000 + 300.000 + 100.000

**Example2: KIN KRE payout after Payout_spend_v is implemented for an Ecosystem App that has 1 spend opportunity only**
Payout_i = [Payout_spend_f + Payout_spend_v]+ Payout_hold_i + Payout_buy_i 
For an App such having only 1 spend opportunity:
[360.000 + 12.000] + 300.000 + 100.000 = 772.000 KIN 
= a decrease of 22.8% of received KIN for that App

**Example3: KIN KRE payout after Payout_spend_j is implemented for an Ecosystem App that has 21+ spend opportunities**
Payout_i = [Payout_spend_f + Payout_spend_v]+ Payout_hold_i + Payout_buy_i 

For an App such having only 1 spend opportunity:
[360.000 + 240.000] + 300.000 + 100.000 = 1.000.000 KIN 
The App, with 21+ spends will get the same Payout_spend_i as in the current KIN KRE 2.0

If this change is implemented, it will lead to a decrease of Supply as most of the Ecosystem Apps in the beginning do not have a lot of spends in-App.

To comply and be eligible to earn from the variable part of the Spend section, Ecosystem Apps will have to provide proactively KF the proof and existence of those valid spends.
-	By providing a list of all the spends within their Apps
-	By providing the technical specifications showing that the spends are technically implemented

The existence of those spends will be audited periodically by Kin Foundation (or some specific independent auditors). The KIN Council could make some pinpoint quality checks from time to time (?)

The adjustment clearly incentivizes the Ecosystem Apps to develop more valid spends. By doing this, Kin Ecosystem Apps users will be more incentivized to spend their KIN in the App. If more spends are confirmed, it might push a certain % of users to actually buy KIN in the App. It is expected that the buying in-app feature of the App will allow this. The amount of KIN distributed by the KRE for the spend part is not increasing as it is a redetermination (60% fixed + 40% variable)

**2. HOLD part**

Proposed KIN KRE formula adaptation (adjustment of hold part)
KIN 2.0 formula (current)
Payout_i = Payout_spend_i + **Payout_hold_**i + Payout_buy_i 

I would not change the amount of KIN earned by the Ecosystem Apps from the hodling section of the formula but I would provide the KIN earned from the holding part 12 months later.
Each week, the amount of KIN that an Ecosystem App will receive from the hold part of the KIN KRE 2.0 can be calculated and sent to a pool. The KIN will be locked there 12 months. 12 months later, the pool will send automatically to the KIN address of the App the KIN earned from the hold section of the KIN KRE. 
Kin Foundation or an external independent entity will ensure that the Pool does distribute the KIN to the Ecosystem partners 12 months later.

Advantages: 
Holding KIN will still make the Apps earn KIN (no changes in the amount to be received)
The KIN earned by holding will be distributed 12 months later so it will actually diminish the KIN supply when KIN KRE payouts are distributed. Diminution of distributed KIN is a reduction of supply. All things being equal, it would have a positive impact on demand.
It would reduce the amount of KIN paid out periodically to the App, so a smaller frozen quantity of KIN will not be dumped.
Solana blockchain will make easier to check the transaction history of a specific KIN address. So it will not be too tedious to check any movement later

Disadvantages:
The Apps would earn less KIN from the KIN KRE due to the HOLD payout being frozen 

**3. BUYING part**

Proposed KIN KRE formula adaptation (adjustment of buying part)
KIN 2.0 formula (current)
Payout_i = Payout_spend_i + Payout_hold_i + Payout_buy_i 

Proposed KIN KRE formula adaptation (adjustment of Buy part)
Payout_buy_i  = Payout_buy_f + Payout_buy_v
where Payout_buy_i = the amount of Payout_buy_f
where Payout_buy_v = % of Payout_buy_i 

The incentives to buy are developing as this current proposal is being written. Kin Ads is being developed and we will see its positive impact on the buying side. Code Wallet will ensure also that the users will be able to buy KIN easily, boosting real demand for KIN.

Ecosystem Apps will need to provide more in-App features to buy KIN or to use other ways to propose the Ecosystem users to buy KIN. As an extra incentive to push the Apps to increase buy In-App KIN , I would propose the following adjustment in case net real demand is positive during a period.

As buying is a critical part of the KIN project on a whole, buying should be rewarded accordingly to any App that is making buying in-App happening. The more people buy KIN in an App, the more the App should be rewarded as buying KIN increasees the value of the whole Ecosystem. I am focusing here on the KIN in-app buying section; other than any Kin bought from Kin Ads and Code Wallet

Adjustment Proposal

Adapting the KIN KRE payout formula (Payout_buy_i) by rewarding Apps that are developing buy in-App features that are successfully increasing the Ecosystem value. The more KIN users buy in-App, the more the App should be rewarded.

•	The total payout_buy_i amount determined by the KIN KRE will remain the same.

•	The total payout_buy_i will be split in two:  Payout_buy_f + payout_buy_v

Where Payout_buy_i amount = Payout_buy_f  amount
Where Payout_buy_v amount is a % of payout_buy_i based on a table below

•	payout_buy_v should never be greater than 200% of payout_buy_i (capped)

The intent is to incentivize the Apps and reward them for the KIN that are bought but also rewarding them with a variable amount of KIN, proportionally to the amount of KIN that are bought by the user in their Apps. 
The more users will buy KIN in an App, the more the Payout_buy_f will increase. Potentially, an App could earn maximum up till 2x the KIN earned from the buying section to avoid oversupply of KIN.

If implemented, the refining of Payout_buy_i will lead to a slight increase of supply for most of the Apps, when they will make users buy more and more KIN. However, the increase of KIN value by fostering and increasing buys in-Apps will counterbalance more the effect of a  slight increase of supply for the buyin section

Payout_buy_v determination
0 buy =  Payout_buy_i = 0 
1 to 5 dollars worth of KIN bought  =    Payout_buy_v = [(Payout_spend_i*20%]
6 to 10 dollars worth of KIN bought =    Payout_buy_v = [(Payout_spend_i*40%]
11 to 50 dollars worth of KIN bought =    Payout_buy_v = [(Payout_spend_i*60%]
51 to 100 dollars worth of KIN bought =    Payout_buy_v = [(Payout_spend_i*80%]
101 to XXXX dollars worth of KIN bought =    Payout_buy_v = [(Payout_spend_i*100%]

Example1: KIN KRE 2.0 current payout
Payout_i = Payout_spend_i + Payout_hold_i + Payout_buy_i 
1M KIN = 600.000 + 300.000 + 100.000 KIN

Example2: KIN KRE payout after Buy_spend_v is implemented in an Ecosystem App where a user 
buys 1$ worth of KIN In-App or
X users buy a total of 1$ worth of KIN

Payout_i = Payout_spend_i + Payout_hold_i + [Payout_buy_f + Payout_buy_v]
Payout_i = 600.000 + 300.000 + [100.000 +  20.000 KIN] = 1.020.000 KIN

Example3: KIN KRE payout after Buy_spend_v is implemented in an Ecosystem App where a user 
buys 20$ worth of KIN In-App or
X users buy a total of 20$ worth of KIN

Payout_i = Payout_spend_i + Payout_hold_i + [Payout_buy_f + Payout_buy_v]
Payout_i = 600.000 + 300.000 + [100.000 +  40.000 KIN] = 1.040.000 KIN

Example4: KIN KRE payout after Buy_spend_v is implemented in an Ecosystem App where a user 
buys 100$ worth of KIN In-App or
X users buy a total of 100$ worth of KIN

Payout_i = Payout_spend_i + Payout_hold_i + [Payout_buy_f + Payout_buy_v]
Payout_i = 600.000 + 300.000 + [100.000 + 100.000 KIN] = 1.100.000 KIN

If this change is implemented, it will lead to a slight increase of Supply the more the Ecosystem Apps are making users buy KIN in-App. But the extra increase of supply, limited to the by section of the KIN equation and capped at 200% maximum of the Payout_buy_i will not make a huge increase of KIN supply. 
Worst case scenario, let’s assume all Apps make 100% of payout_buy_v -> this will just lead to an increase of 10% of all KIN supply overall based on my example (1.100.000 KIN vs 1.000.000 KIN from current KRE)

To comply and be eligible to earn from the variable part of the buy section, Ecosystem Apps may provide proactively KF the proof and existence of those valid buys.

-	By providing a report of all the KIN bought within their Apps (could be maybe automated with Solana blockchain?)

The existence of those buys will be audited periodically by Kin Foundation (or some specific independent auditors) 

Advantages:
The adjustment clearly incentivizes the Ecosystem Apps devs to do all they can to push users to buy KIN in-App. By doing this adjustment, Kin Ecosystem Apps will be more incentivized to make users buy KIN in the App. 

Disadvantages:
A slight increase in distributed KIN supply, that would be capped at 200% of the amount distributed by the buy track.

Conclusion:
1)	Spend track: Adjustment of KRE distributed. Considering a fixed amount and variable amount to be distributed based on number of spends made available. Spend track volume of KIN does not change. It is just a redetermination
Decrease of KIN Supply foreseen at the beginning

2)	Hold track: no changes but HOLD payout to be sent to a pool and locked there for 12 months. Amount distributed 12 months later; restricting a bit the KIN supply distributed periodically by the KRE that would lead to a decrease of the amount of KIN dumps periodically on Exchanges

3)	Buy track: Adjustment of KRE distributed. Including a variable amounts to be distributed. Slight increase of KIN Supply foreseen on the mid term when all Apps will allow more and more KIN buy in-app.

If we take 1. 2. And 3., the net difference would be a slight adjustment of the KIN KRE formula in favor of Demand but the Ecossytem Apps will be more pushed and motivated to develop the KIN philosophy further

**Comment by hitwill** [comment]
Issue does not affect current KRE
