### ISSUE TITLE
KIN Community to develop the Partners network and push proactively KIN awareness on social media

### ISSUE THREAD

**Issue by Polype01** [kinecosystem/rewards-engine#77]
From my experience of mobile games player and as an internet addict, I remark sometimes some games where the use of KIN would be great. You can learn a lot about an App Economy just by playing daily gatcha mobile games. Have you ever played Brave Frontier, Final Fantasy Brave Exvius... ? Those are just examples and there are a lot of them available on iOS or Android.

Those games reward periodically players by giving them daily rewards, Gems, diamonds, Gils...(the internal In-App currency) when the player/user performs certain tasks. Those games have an internal webshop where you can buy those internal currencies in exchange of FIAT. By checking the value ratio of a Gams, diamond.vs. FIAT (Dollar, Euro...), you can determine the perceived value of 1 Gem.

My assumption is that most of crypto people like to play games and in order to have partners joining the Ecosystem, we should not rely solely on KF. The KIN Council and/or community members (who like games and KIN obviously) should be entitled to contact proactively potential KIN partners on behalf of KIN Foundation. 
Presentation materials with KIN values and objectives would be provided by KF on a sharedrive (GitHub) and those materials would be used by any person motivated to present KIN to potential partners/games editors... 

My proposal#1 would be to have Kin Foundation budgetize one specific grant "KIN Business development" (10b KIN for example) This grant would be used to give commissions to KIN Council and/or community members who managed to attract a partner into the Ecosystem. The amount of the commission would be based on the number of active users of the joining Partner and it would be paid in the next 12 months of the signature, to avoid any negative impact on supply.
If a community member wants to give it a try and not knowing how to do it, he/she can try to present KIN to the Partner with the help of a specific KIN Council member. 

More partners, more potential people spending/earning KIN, more potential people willing to buy KIN -> more chances to have real demand increase through KIN awareness.

What do you think?

My proposal #2 would be to have some KIN Community people who are very active on specific social media to receive specific grants periodically in exchange of their efforts to expose and hype KIN a bit further.

These people would do some easy marketing community actions on twitter/reddit/telegram to make KIN better known and to make some little hype and make some KIN presence on those platforms. KIN Council members should be triggering these actions:

- User actions: If you like a KF post -> Any number of users who liked the post will receive randomly some KIN
- Referrals actions: If you tweet a post from KF + put three persons in copy -> Any number of users will receive randomly some KIN
- Some little fun games where the first winners could get some KIN.
- Riddle answering...
....
You name it. imagination is the limit.

It would make KIN look more dynamic, more hype and fun. 
If the target of KIN is the youth in general, KF should really ensure that the target will notice KIN on all social media. 
People who will participate to those actions will just want some free KIN but at least, they will have an awareness of KIN through those fun actions.

**Comment by RichieDotexe** [comment]
Interesting proposal, I would hope in the future that the KRE would be enough of an intensive for apps to join without having to offer money. I am leaning more towards Proposal #2.
