### ISSUE TITLE
Suggestion - Change KRE 2.2.1. to include ALL revenue from Kin Ads

### ISSUE THREAD

**Issue by showered** [kinecosystem/rewards-engine#79]
I'd like to suggest a tweak to the KRE 2.2.1 proposal. 

Instead of specifying "Banner Ads", I think it would be better to include revenue from all forms of advertising within Kin Ads.  For example Interstitials and Offer Walls.

@kikengineering

**Comment by kikengineering** [comment]
Hey @showered 
The original reason for the change was related to banner ads (that's just the specific case we discussed with Kin Ads), but it does apply to all forms of advertising within Kin Ads (i.e. interstitials and offer walls would count towards the buy track). There's 1-2 of typos we need to fix anyway, so we'll add a few clarifying words on this.
Thanks.

**Comment by kikengineering** [comment]
PR is up
https://github.com/kinecosystem/rewards-engine/pull/80
Thanks again for the feedback. Hopefully it's more clear now.
