### ISSUE TITLE
KRE v3 Suggestion - Favor High Quality "Approved" User Experiences

### ISSUE THREAD

**Issue by Ghost-Type** [kinecosystem/rewards-engine#90]
While KRE 3.0 opts to maintain simplicity and therefore not recommend any additional interventions in the Spend Track to promote higher-quality spends, here is a potential idea that might be considered:

**Problem:** Use case quality varies wildly, as does economic value contributed. As such the next iteration of the KRE should seek to not only incentivize volume, but also quality.

**Solution:** Approved Implementations (KRE multiplier)
Similar to a “Seal of Approval”, the Kin Foundation should seek to provide maximum rewards and official recognition to applications with exceptional use cases and user experiences. This will differentiate use cases deemed by the community to be good examples of Kin utility. By providing higher incentive to create premium use cases, the ecosystem should see a drastic increase in quality user experiences. 

**Implementation:** By default, final KRE payouts could be set to a x0.5 multiplier in order to provide incentive headroom for premium experiences. Then, a quality assurance board (KCC?) could leverage an initial ecosystem app review in order to single out currently existing exceptional use cases that provide (i) a great user experience, (ii) genuine utilitarian value to Kin as a currency, and (iii) are not designed to game the Kin Rewards Engine in any way, or better yet are optimized to create value for Kin. These experiences would be unthrottled reward wise (an effective x2 multiplier as everything was cut in half with the 0.5 multiplier) and allowed to earn higher rewards. This rewards developers for taking the time to create thoughtful and useful experiences and curbs the effectiveness of use case gaming (e.g. giving users kin then taking it back, buying kin to give to users to then take right back), while not inhibiting the developers’ ability to implement whatever use case they wish. This should also be applied to whitelisted buy modules, as user experience and gaming are still potential issues, where quality experiences that create value should be prioritized over others.

The QA product council would be able to recommend improvements based on their findings. Thereafter, application developers could apply to have any newly implemented use cases gain the "Approved Implementation" seal and earn full rewards. Any developers that are unhappy about the change would simply need to improve their user experience to the specifications and recommendations of the quality assurance board (remove gaming, disallow empty balance forgiveness, etc.).

**Comment by hitwill** [comment]
Interesting idea - Perhaps rather than throttling from the get go, a multiplier is given for apps that have premium experiences? Apps wanting to get the multiplier could apply and be approved based on based on more stringent criteria

**Comment by dillontking** [comment]
Adding a federation to determine eligibility for KRE rewards was proposed in the original RFC document and never followed up on. How could we organize and establish such a body beyond just delegating the responsibilities to the Kin Foundation board? How should the federation be elected? Should stake play a role?

**Comment by kikengineering** [comment]
Posted in the other thread but repeating here:

In terms of this idea, this and a few others were proposed in order to increase incentives for developers making compelling use cases. While we 100% agree that we wish to reward apps with the best use cases more, what we've found over the last year and a half of running the KRE is that anything with subjective monitoring is very challenging and we tried very hard to remove as much of this from the KRE as possible. It greatly increases the overhead of computing payouts as there is a large number of apps which make very frequent changes. All of these updates and changes need to be communicated to the payout team looking at blockchain data, and adjustments need to be made accordingly. More importantly, as the community continues to scale (as we hope it will) this will become increasingly difficult to automate and decentralize, and we will need a large team constantly assessing apps on a weekly basis.

**Comment by Ghost-Type** [comment]
thanks for the replies, sorry i was away for a while 

after reflecting on these replies here is what i think:

> Interesting idea - Perhaps rather than throttling from the get go, a multiplier is given for apps that have premium experiences? Apps wanting to get the multiplier could apply and be approved based on more stringent criteria

good idea, this was actually my first thought of how this could work too, but the issue then is that apps receiving money for easy spends today don't necessarily have an incentive to change their behavior, similar to tourism an extra pot might not do much at all and current participants may be satisfied with the way things are

> Adding a federation to determine eligibility for KRE rewards was proposed in the original RFC document and never followed up on. How could we organize and establish such a body beyond just delegating the responsibilities to the Kin Foundation board? How should the federation be elected? Should stake play a role?

this could be one way to do it. i was imagining that the kin community council might be able to play a role, but maybe the a new body could be put together. making kin=credibility in this arena however might be a bad idea, as speculators may simply evaluate things based on their own interests. a federation for this would likely need to be a balanced committee  of developers, holders, and kin team.

> In terms of this idea, this and a few others were proposed in order to increase incentives for developers making compelling use cases. While we 100% agree that we wish to reward apps with the best use cases more, what we've found over the last year and a half of running the KRE is that anything with subjective monitoring is very challenging and we tried very hard to remove as much of this from the KRE as possible. It greatly increases the overhead of computing payouts as there is a large number of apps which make very frequent changes. All of these updates and changes need to be communicated to the payout team looking at blockchain data, and adjustments need to be made accordingly. More importantly, as the community continues to scale (as we hope it will) this will become increasingly difficult to automate and decentralize, and we will need a large team constantly assessing apps on a weekly basis.

while i agree with your premise, i think this conclusion is the opposite of mine. if the KRE is to become decentralized, then it will be even more susceptible to attack at scale from low quality spends. the kin foundation will not be able to police the ecosystem, and KRE gaming, gambling, and more could take over the economy. it is inevitable that some level of whitelisting happen unless quality be allowed to fall through the floor, similar to the whitelisting process for buy modules. individual applications would have to be evaluated as they come in, and changes would only be accommodated for at the convenience of the kin foundation.

**Comment by hitwill** [comment]
Closed based on comments of scale by kikengineering. A good proposal but difficult to scale. We have found that providing grants to get apps to update to more useful spends also works similar to the proposal.
