### ISSUE TITLE
Proposal for the KRE 3.0 Improvement (lock-in  mechanism)

### ISSUE THREAD

**Issue by Raketenernie** [kinecosystem/rewards-engine#92]
**Introduction:**

All proposals so far focus on trying to fix the distribution of KIN over the KRE by different methods. However, the ultimate challenge or problem of the KRE, namely setting the amount of KIN rewarded to the exact right level so the ecosystem is in equilibrium has been untouched. 

What we have seen (ex -ante) is that over a period of a year the KRE has rewarded more Kin that the ecosystem actually was able to absorb. Over time the KRE Reward System oversupplied the ecosystem with KIN. One way to demonstrate this fact, is looking at the Net Dollars Bought (NDB) which expresses the kin bought by dollars for goods and services within the ecosystem, less all KIN paid by the Kin Foundation through the KRE and grants. The NDB steadily decreased reaching a new negative delta of 300+ Billion Kin.

To make it clear how big this oversupply is:

Given ceteris paribus, even if you would stop KIN KRE right now, with the current KIN spend per day (GDP) of 200 Mio. it would take 1.500 days (over 4 Years) to cover up the 300 billion of NDB in terms of oversupply.

**The idea to fix this problem:**

In the past my approach was either to reduce the amount , change it to dollars, reward only certain vectors,etc.. and if you read most proposals they all about adjusting vectors not the amount. However there is an alternative way / a work around fixing the problem of setting the KRE amount right. 

How about to implement a temporarily lock-in / freeze mechanism for the oversupply of Kin caused by the KRE.

**How would this mechanism work**?

For each month there has to be an estimation of the absorbment level of Kin. We could use  B/I ratio as one indicator  as the B/I ratio determines if the ecosystem is sustainable, and you can look ex ante at the NDB (looking back past months) enabling you to estimate more or less how much can be absorbed the following month. 

This estimation will define your maximum possible Kin payout over the KRE month by month. The difference between the absorbment level and the inital Kin reward of the KRE determines your oversupply which will be locked-up or froozen. We look here at the total sum, so it would affect all apps the same.

To demonstrate it better, I will just use dummy figures. Lets say our monthly absorbment level of the ecosystem is 1 Bn Kin. Where as the total amount of KRE rewards is 1.5 Bn Kin. So for that month we would have an oversupply of 0.5 bn Kin. Now instead of rewarding this 0.5 BN Kin, we would freeze and lock them up, leaving the ecosystem in equilibrium.

**Where would be the "froozen" Kin be locked-up?**

There is two ways of doing it:

We create for each app / dev a shadow account, where the froozen kin is stored , so everyone can see how much kin is froozen for each single app

We create one escrow account for the total sum locked, this would keep the process simple and would be easier to monitor / less labour intensive.

**How long would this Kin be froozen / locked up?**

Given the assumoption of a maturing ecosystem the GDP should and will grow. This will lead that the absorbment level will increase over time. Eventually  the absorbment level is greater than the initial KRE payouts. 

To illustrate with my example from above:

Total Absorbment level 2 Bn Kin vs. 1.5 Bn KIN KRE rewards --> leading to 0.5 Bn Kin defecit /undersupply. The difference than will be filled up with Kin from the "froozen, locked-up Kin) until these reserves run out. This has the positive side effect that the ecosystem stays longer in equilibrium and apps do not immediately have to top up using real dollars. To increase the incentive for apps to actually to participate and to bind them to Kin it is important to make this "froozen supply of Kin" conditional.
For apps that drop KIN in the mean time will lose their right to claim this "locked-in" KIN. Like that, the incentive for apps to participate growth as longer they participate. 

**Why should we introduce such a mechanism what are the benefits?**

1.  We stop immediately the oversupply of Kin, which will put the ecosystem in equilibrium and will lead to growth of value of Kin 
     and will stop downward volatility and velocity.

2.  Apps still receive the same rewards as before just with a time delay. Absolutely seen there is no financial cut here for any 
     participant, so the financial incentive to use Kin remains the same for all apps. So the threat of apps droping out could be 
     minimized.

3.  By freezing some of the Kin KRE reward you automatically stake Kin for the Apps, however in the exact amount giving you a 
     balanced ecosystem. This then as longer the apps participate creates an incentive to stay , since there froozen KIN reserve is 
     growing month by month, combined with a steady increase of value of Kin. Apps eventually want that reserve , it would act as 
     a savings / bonus account / program.

4.  It is a very easily implement mechanism which can be easily and very transparent demonstrated

5.  It would lead to growth as we would generate an envrionment which is in equilibrium where new fresh investment money by 
     upcoming listings could bring Kins value up. We have to create the feeling by each user , dev, and investor that Kin is 
     something special, something precious. An environment where the Kin I hold today is most definetly worth more by 
     tomorrow. If we get to this stage where we Kin moves away from a price erosion then it is only a question of time that 
     liquidity will grow and more important devs want and will participate and implement earns 
     and spends that have a real economic impact. In any economy inflation and volatility is toxin and we need to fix this.
    

**How would the formular for the mechanism look like?**

A = Absorbment level per month --> which will be the result of B/I ratio and the development of the NDB

For example (with dummies)for payouts December: 

1. Initial planed KRE amount for December = 20 bn KIN --> Y(KRE) = 20 Bn KIN
2. NDB month by month shows you from October to November a negative delta of 10 bn kin.  --> NDB(month) = 10 Bn Kin
3. The B/I ratio multiplied by the initial planed  KRE amount --> Y(KRE)* B/I ratio = 0,6 * 20 Bn Kin = 12 Bn Kin
4. Oversupply --> O = Y(KRE)-(Y(KRE)*NDB) = 20 Bn Kin - 12 Bn Kin = 8 Bn Kin oversupply
5. Absorbment level (A) -->  Calculate an average = ( O+NDB(month))/2 = (10 Bn Kin + 8 Bn Kin)/2 = 9 Bn Kin  --> oversupply 
   which then goes into the lock-up  / froozen escrow account and your absorbment level would be A = 11 Bn Kin

Y(KRE)= Total initial planed KRE payout per month

X = Kin froozen --> send to escrow account

Z = Kin in escrow account

Y-A= X

Then if Y(KRE)-A <0 ; --> negative (defecit) it gets filled up by Kin from Z --> aZ if X<0; X+aZ= 0 --> a = X/Z

I soley look here at the supply not the distribution / vectors themselves. So for the future the KRE supply paid to apps is always if Y-A<0 ; Y-A+aZ

Enjoy and open for discussions

**Comment by hitwill** [comment]
An interesting proposal - especially towards the end state of the ecosystem. For now, apps are allowed to have an oversupply of Kin but over time, we should control the inflation rate more.

Even without intervention, a mature economy will end up burning more Kin than is supplied by the KRE
