### ISSUE TITLE
Suggestion: KRE Roadmap - Long Term Economic Planning

### ISSUE THREAD

**Issue by Ghost-Type** [kinecosystem/rewards-engine#95]
So far, the KRE has been iterated upon much like a product feature, by learning from effects after shipping and tweaking further in hopes of achieving a "fit" with the next release. What has become apparent, however, is that the economy will grow in different phases, and that we will have different needs for each of those phases. For example, KRE v3 comes full circle to incentivizing the mass distribution and adoption of Kin by users, but after that there will once again be a need to incentivize the creation of use cases for those users to spend Kin on, and after that there will be a need to incentivize those who create the most purchasing power. 

I think that the Kin Foundation, Kik, and community of developers and supporters should put their heads together to figure out what the long-term strategy is for the Kin Rewards Engine, which would entail two things:

1. Work should begin on Kin Rewards Engine v4 and other iterations thereafter NOW, not in the days leading up to a potential change or once Kik has submitted a proposal. The discussion should be heavily promoted and great proposals incentivized. This will allow maximum contribution and the most number of high quality ideas. This is superior to calling developer meetings where participants are asked on the spot to come up with changes, which usually results in very obvious low-hanging fruit to be submitted with little to no long-term foresight, and minimum relevance to the specific changes that are being sought. A larger and more intentional time window would also allow developers to have more time to give their input and prepare for changes. Changing quarterly doesn't help developers if they still only have a month to prepare and propose changes, much less innovate alongside Kin Foundation and Kik.

2. In addition to starting work earlier on future KRE iterations, a long-term roadmap and "big picture strategy" should be developed in collaboration with the community in order to  guide the development of those iterations. A template for what the economy is trying to achieve in the long-term, as opposed to simply the next few months, will allow KRE iterations to be more robust, and thus more effectively achieve objectives for the project.

**Comment by nielskijf** [comment]
Could be a good idea to work with design principles for these phases, also visualization of the 'current' KRE focus helps, so people can easily learn what contributes most to the current phase.

**Comment by hitwill** [comment]
Good points on future iterations, which is how we currently look at the KRE.
